// Image model definitions (Part 1: OpenAI, Stability, Replicate, Fal)
export const IMAGE_MODELS = [
  {
    providerName: "openai",
    name: "GPT Image 1",
    modelId: "gpt-image-1",
    type: "image",
    capabilities: "t2i,i2i,edit,inpaint",
    description: "Best image quality, great instruction following. Supports text-to-image, image editing, and inpainting.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.04–0.167/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "openai",
    name: "DALL-E 3",
    modelId: "dall-e-3",
    type: "image",
    capabilities: "t2i",
    description: "High quality text-to-image with vivid and natural styles.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "standard", style: "vivid", n: 1 }),
    priceInfo: "$0.04–0.08/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "openai",
    name: "GPT Image 2",
    modelId: "gpt-image-2",
    type: "image",
    capabilities: "t2i,edit,inpaint",
    description: "Latest GPT Image 2 with text rendering, multi-reference editing, and character consistency. Supports edits endpoint.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.04–0.167/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "openai",
    name: "ChatGPT 4o Image",
    modelId: "chatgpt-4o-image",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "ChatGPT 4o's native image generation with superior instruction following.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.02–0.08/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "openai",
    name: "DALL-E 2",
    modelId: "dall-e-2",
    type: "image",
    capabilities: "t2i,edit,variations",
    description: "Legacy model with editing and variation support.",
    defaultParams: JSON.stringify({ size: "1024x1024", n: 1 }),
    priceInfo: "$0.016–0.020/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "stability",
    name: "Stable Image Ultra",
    modelId: "stable-image-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Highest quality text-to-image generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "stability",
    name: "SD 3.5 Large",
    modelId: "stable-diffusion-3.5-large",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 3.5 Large — high quality open-source model.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.065/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "stability",
    name: "SD 3.5 Large Turbo",
    modelId: "stable-diffusion-3.5-large-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Faster version of SD 3.5 Large.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "stability",
    name: "Stable Image Core",
    modelId: "stable-image-core",
    type: "image",
    capabilities: "t2i",
    description: "Fast text-to-image generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "stability",
    name: "SDXL 1.0",
    modelId: "sdxl-1.0",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion XL — popular open model.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "stability",
    name: "Creative Upscale",
    modelId: "creative-upscale",
    type: "image",
    capabilities: "upscale",
    description: "4x creative upscaling with detail enhancement.",
    defaultParams: JSON.stringify({ output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "stability",
    name: "Erase/Inpaint",
    modelId: "stable-image-erase",
    type: "image",
    capabilities: "inpaint",
    description: "Remove objects or inpaint masked areas.",
    defaultParams: JSON.stringify({ output_format: "png" }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "stability",
    name: "SD 4",
    modelId: "stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 — latest generation with superior quality and prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "stability",
    name: "SD 3.5 Medium",
    modelId: "stable-diffusion-3.5-medium",
    type: "image",
    capabilities: "t2i",
    description: "SD 3.5 Medium — balanced quality and speed",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },

  {
    providerName: "replicate",
    name: "FLUX 1.1 Pro",
    modelId: "black-forest-labs/flux-1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "Best open-ish model, excellent quality.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "replicate",
    name: "FLUX Dev",
    modelId: "black-forest-labs/flux-dev",
    type: "image",
    capabilities: "t2i",
    description: "Great quality/cost ratio, open weights.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "replicate",
    name: "FLUX Schnell",
    modelId: "black-forest-labs/flux-schnell",
    type: "image",
    capabilities: "t2i",
    description: "Fastest FLUX model, very cheap.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1, num_inference_steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "replicate",
    name: "FLUX Kontext Pro",
    modelId: "black-forest-labs/flux-kontext-pro",
    type: "image",
    capabilities: "edit,inpaint",
    description: "Image editing and inpainting with FLUX.",
    defaultParams: JSON.stringify({ num_outputs: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "replicate",
    name: "Ideogram v3",
    modelId: "ideogram-ai/ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering in images.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1" }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "replicate",
    name: "SD 4",
    modelId: "stability-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Latest Stable Diffusion 4 via Replicate",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "replicate",
    name: "FLUX 2 Pro",
    modelId: "black-forest-labs/flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 Pro with superior quality and text rendering",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "replicate",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev, open weights with improved quality",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "replicate",
    name: "Seedream 4.0",
    modelId: "bytedance/seedream-4",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.0 — unified generation and editing, up to 4MP",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },

  {
    providerName: "replicate",
    name: "Seedream 4.5",
    modelId: "bytedance/seedream-4.5",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 — improved multi-image editing, accurate subject ID",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 10,
  },

  {
    providerName: "replicate",
    name: "Nano Banana 2",
    modelId: "google/nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 — Pro-level quality with lightning speed",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 11,
  },

  {
    providerName: "replicate",
    name: "Recraft V3",
    modelId: "recraft-ai/recraft-v3",
    type: "image",
    capabilities: "t2i",
    description: "Vector + raster with long text and precise positioning",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 12,
  },

  {
    providerName: "replicate",
    name: "Playground v3",
    modelId: "playgroundai/playground-v3",
    type: "image",
    capabilities: "t2i",
    description: "Playground v3 — great for creative and commercial work",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 13,
  },

  {
    providerName: "fal",
    name: "FLUX Pro v1.1",
    modelId: "fal-ai/flux-pro/v1.1",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via Fal.ai — top quality.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "fal",
    name: "FLUX Dev",
    modelId: "fal-ai/flux/dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Fal.ai.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "fal",
    name: "FLUX Schnell",
    modelId: "fal-ai/flux/schnell",
    type: "image",
    capabilities: "t2i",
    description: "Fastest FLUX via Fal.ai.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1, num_inference_steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "fal",
    name: "FLUX Kontext Pro",
    modelId: "fal-ai/flux-kontext-pro",
    type: "image",
    capabilities: "edit",
    description: "Image editing with FLUX Kontext.",
    defaultParams: JSON.stringify({ num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "fal",
    name: "FLUX Realism",
    modelId: "fal-ai/flux-realism",
    type: "image",
    capabilities: "t2i",
    description: "Realistic photo generation with FLUX.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "fal",
    name: "FLUX 2 Pro",
    modelId: "fal-ai/flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 with superior quality and text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "fal",
    name: "FLUX 2 Dev",
    modelId: "fal-ai/flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev, improved over v1",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "fal",
    name: "Ideogram v3",
    modelId: "fal-ai/ideogram/v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering via Fal.ai",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "fal",
    name: "SD 4",
    modelId: "fal-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Fal.ai",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 9,
  },

  {
    providerName: "fal",
    name: "FLUX 2 Dev Turbo",
    modelId: "fal-ai/flux-2-dev-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Fal's distilled FLUX 2 Dev — 10x cheaper, 6x more efficient",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.01/image",
    isDefault: false,
    sortOrder: 10,
  },

  {
    providerName: "fal",
    name: "Seedream 4.0",
    modelId: "fal-ai/bytedance/seedream/v4/text-to-image",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.0 via Fal — generation + editing in one model",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 11,
  },

  {
    providerName: "fal",
    name: "Seedream 4.5",
    modelId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 via Fal — improved editing accuracy",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 12,
  },

  {
    providerName: "fal",
    name: "FLUX 1.1 Pro Ultra",
    modelId: "fal-ai/flux/v1.1-pro-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Ultra-high quality FLUX Pro variant with enhanced detail",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 13,
  },

  {
    providerName: "fal",
    name: "FLUX Anime",
    modelId: "fal-ai/flux/anime",
    type: "image",
    capabilities: "t2i",
    description: "Anime-optimized FLUX model for illustration and manga styles",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 14,
  },

  {
    providerName: "fal",
    name: "FLUX 2 Pro Ultra",
    modelId: "fal-ai/flux-2-pro-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Highest quality FLUX 2 variant with maximum detail and text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.12/image",
    isDefault: false,
    sortOrder: 15,
  },

  {
    providerName: "fal",
    name: "Imagen 4",
    modelId: "fal-ai/google/imagen4",
    type: "image",
    capabilities: "t2i",
    description: "Google Imagen 4 via Fal — photorealistic with excellent text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: false,
    sortOrder: 16,
  },

  {
    providerName: "fal",
    name: "Kandinsky 3.1",
    modelId: "fal-ai/kandinsky-3.1",
    type: "image",
    capabilities: "t2i",
    description: "Kandinsky 3.1 — popular Russian open model with vibrant colors",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 17,
  },

  {
    providerName: "fal",
    name: "Nano Banana 2",
    modelId: "fal-ai/google/nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google Nano Banana 2 via Fal — Pro-level quality at speed",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 18,
  },
];
