// Video model definitions exposed by adapters in src/app/api/generate/video.
// Keep this list intentionally conservative: a model is shown only when the
// app has a matching request and polling implementation.
export const VIDEO_MODELS = [
  {
    providerName: 'replicate',
    name: 'Seedance 2.0',
    modelId: 'bytedance/seedance-2.0',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'ByteDance Seedance 2.0 with native audio and first/last-frame guidance.',
    defaultParams: JSON.stringify({
      duration: 5,
      resolution: '720p',
      aspect_ratio: '16:9',
      generate_audio: true,
    }),
    priceInfo: 'Provider pricing',
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: 'fal',
    name: 'Seedance 2.0',
    modelId: 'bytedance/seedance-2.0/text-to-video',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Seedance 2.0 through fal with native audio and automatic image-to-video routing.',
    defaultParams: JSON.stringify({
      duration: '5',
      resolution: '720p',
      aspect_ratio: '16:9',
      generate_audio: true,
    }),
    priceInfo: 'Per-second via fal',
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: 'fal',
    name: 'Seedance 2.0 Fast',
    modelId: 'bytedance/seedance-2.0/fast/text-to-video',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Faster Seedance 2.0 generation through fal.',
    defaultParams: JSON.stringify({
      duration: '5',
      resolution: '720p',
      aspect_ratio: '16:9',
      generate_audio: true,
    }),
    priceInfo: 'Per-second via fal',
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: 'runway',
    name: 'Gen-4.5',
    modelId: 'gen4.5',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Runway Gen-4.5 for text-to-video and image-to-video generation.',
    defaultParams: JSON.stringify({ duration: 5, ratio: '1280:720' }),
    priceInfo: 'Provider pricing',
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: 'runway',
    name: 'Gen-4 Turbo',
    modelId: 'gen4_turbo',
    type: 'video',
    capabilities: 'i2v',
    description: 'Runway image-to-video generation with flexible 2–10 second duration.',
    defaultParams: JSON.stringify({ duration: 5, ratio: '1280:720' }),
    priceInfo: 'Provider pricing',
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: 'luma',
    name: 'Ray 2',
    modelId: 'ray-2',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Luma Ray 2 high-quality text-to-video and image-to-video generation.',
    defaultParams: JSON.stringify({
      duration: '5s',
      resolution: '720p',
      aspect_ratio: '16:9',
    }),
    priceInfo: 'Provider pricing',
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: 'luma',
    name: 'Ray 2 Flash',
    modelId: 'ray-flash-2',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Faster Luma Ray 2 video generation.',
    defaultParams: JSON.stringify({
      duration: '5s',
      resolution: '720p',
      aspect_ratio: '16:9',
    }),
    priceInfo: 'Provider pricing',
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: 'google-aistudio',
    name: 'Veo 3.1',
    modelId: 'veo-3.1-generate-preview',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Google Veo 3.1 cinematic video generation with native audio.',
    defaultParams: JSON.stringify({ aspect_ratio: '16:9' }),
    priceInfo: 'Provider pricing',
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: 'google-aistudio',
    name: 'Veo 3.1 Fast',
    modelId: 'veo-3.1-fast-generate-preview',
    type: 'video',
    capabilities: 't2v,i2v',
    description: 'Faster Google Veo 3.1 generation with native audio.',
    defaultParams: JSON.stringify({ aspect_ratio: '16:9' }),
    priceInfo: 'Provider pricing',
    isDefault: false,
    sortOrder: 2,
  },
];
