// Provider definitions for the app (static, no database needed)
export const PROVIDERS = [
  {
    id: "openai",
    name: "openai",
    displayName: "OpenAI",
    description: "GPT-Image-1, DALL-E 3 & 2 — Best image quality and instruction following",
    baseUrl: "https://api.openai.com/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "sk-...",
    icon: "openai",
    color: "#10a37f",
    website: "https://platform.openai.com",
    sortOrder: 1,
  },
  {
    id: "stability",
    name: "stability",
    displayName: "Stability AI",
    description: "Stable Diffusion 3.5, SDXL, inpainting, upscaling, and style control",
    baseUrl: "https://api.stability.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "sk-...",
    icon: "stability",
    color: "#7c3aed",
    website: "https://platform.stability.ai",
    sortOrder: 2,
  },
  {
    id: "replicate",
    name: "replicate",
    displayName: "Replicate",
    description: "Flux, SD, and hundreds of open-source models — huge catalog",
    baseUrl: "https://api.replicate.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "r8_...",
    icon: "replicate",
    color: "#a855f7",
    website: "https://replicate.com",
    sortOrder: 3,
  },
  {
    id: "fal",
    name: "fal",
    displayName: "Fal.ai",
    description: "Flux, SD, Ideogram, Kling, Pika, Wan — widest model selection with async queue",
    baseUrl: "https://queue.fal.run",
    authHeader: "Authorization",
    authPrefix: "Key",
    keyFormat: "fal-key",
    icon: "fal",
    color: "#6366f1",
    website: "https://fal.ai",
    sortOrder: 4,
  },
  {
    id: "together",
    name: "together",
    displayName: "Together AI",
    description: "FLUX models (FREE Schnell), SDXL, Ideogram — OpenAI-compatible API",
    baseUrl: "https://api.together.xyz",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "together-key",
    icon: "together",
    color: "#06b6d4",
    website: "https://together.ai",
    sortOrder: 5,
  },
  {
    id: "fireworks",
    name: "fireworks",
    displayName: "Fireworks AI",
    description: "FLUX Schnell/Dev, SDXL — fast inference, OpenAI-compatible API",
    baseUrl: "https://api.fireworks.ai/inference",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "fireworks-key",
    icon: "fireworks",
    color: "#f97316",
    website: "https://fireworks.ai",
    sortOrder: 6,
  },
  {
    id: "ideogram",
    name: "ideogram",
    displayName: "Ideogram",
    description: "Ideogram 3.0 — Best text rendering in images, great quality",
    baseUrl: "https://api.ideogram.ai",
    authHeader: "Api-Key",
    authPrefix: "",
    keyFormat: "ideogram-key",
    icon: "ideogram",
    color: "#ec4899",
    website: "https://developer.ideogram.ai",
    sortOrder: 7,
  },
  {
    id: "google-aistudio",
    name: "google-aistudio",
    displayName: "Google AI Studio",
    description: "Gemini + Imagen models via API key — for individual developers",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authHeader: "x-goog-api-key",
    authPrefix: "",
    keyFormat: "AIza...",
    icon: "google-aistudio",
    color: "#4285f4",
    website: "https://aistudio.google.com/api-keys",
    sortOrder: 8,
  },
  {
    id: "google-vertex",
    name: "google-vertex",
    displayName: "Google Vertex AI",
    description: "Enterprise-grade Imagen & Veo via Vertex AI — service account or OAuth2 authentication",
    baseUrl: "https://us-central1-aiplatform.googleapis.com/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "service-account JSON or OAuth2 token",
    icon: "google-vertex",
    color: "#34a853",
    website: "https://console.cloud.google.com/vertex-ai",
    sortOrder: 17,
  },
  {
    id: "runway",
    name: "runway",
    displayName: "Runway",
    description: "Gen-4 Turbo — Best-in-class video generation with flexible duration",
    baseUrl: "https://api.dev.runwayml.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "runway-key",
    icon: "runway",
    color: "#22c55e",
    website: "https://dev.runwayml.com",
    sortOrder: 9,
  },
  {
    id: "luma",
    name: "luma",
    displayName: "Luma AI",
    description: "Ray2 — High quality video generation with low latency",
    baseUrl: "https://api.lumalabs.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "luma-key",
    icon: "luma",
    color: "#8b5cf6",
    website: "https://lumalabs.ai",
    sortOrder: 10,
  },
  {
    id: "huggingface",
    name: "huggingface",
    displayName: "Hugging Face",
    description: "Free tier access to FLUX, SD, and hundreds of open models",
    baseUrl: "https://api-inference.huggingface.co/models",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "hf_...",
    icon: "huggingface",
    color: "#ffd21e",
    website: "https://huggingface.co",
    sortOrder: 11,
  },
  {
    id: "leonardo",
    name: "leonardo",
    displayName: "Leonardo.ai",
    description: "Phoenix, Kino XL, Vision XL — cinematic and photorealistic images",
    baseUrl: "https://cloud.leonardo.ai/api/rest/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "leonardo-key",
    icon: "leonardo",
    color: "#a855f7",
    website: "https://leonardo.ai",
    sortOrder: 12,
  },
  {
    id: "recraft",
    name: "recraft",
    displayName: "Recraft AI",
    description: "Recraft V3 — Vector + raster, style control, long text support",
    baseUrl: "https://api.recraft.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "recraft-key",
    icon: "recraft",
    color: "#14b8a6",
    website: "https://recraft.ai",
    sortOrder: 13,
  },
  {
    id: "bfl",
    name: "bfl",
    displayName: "Black Forest Labs",
    description: "FLUX Pro, Kontext — Direct API from the FLUX creators",
    baseUrl: "https://api.bfl.ml",
    authHeader: "X-Key",
    authPrefix: "",
    keyFormat: "bfl-key",
    icon: "bfl",
    color: "#ef4444",
    website: "https://bfl.dev",
    sortOrder: 14,
  },
  {
    id: "aimlapi",
    name: "aimlapi",
    displayName: "AI/ML API",
    description: "400+ models aggregator — OpenAI-compatible, free tier available",
    baseUrl: "https://api.aimlapi.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "aiml-key",
    icon: "aimlapi",
    color: "#f59e0b",
    website: "https://aimlapi.com",
    sortOrder: 15,
  },
  {
    id: "seedance",
    name: "seedance",
    displayName: "Seedance (ByteDance)",
    description: "Seedance 2.0 — High quality video generation with cinematic workflows",
    baseUrl: "https://api.seedance.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "seedance-key",
    icon: "seedance",
    color: "#00d4aa",
    website: "https://seedance.ai",
    sortOrder: 16,
  },
];


import { IMAGE_MODELS as IMAGE_MODELS_1 } from './providers-image-data-1';
import { IMAGE_MODELS as IMAGE_MODELS_2 } from './providers-image-data-2';
import { VIDEO_MODELS } from './providers-video-data';

export const MODELS = [...IMAGE_MODELS_1, ...IMAGE_MODELS_2, ...VIDEO_MODELS];
