// Provider definitions for seeding the database
export const PROVIDERS = [
  {
    name: "openai",
    displayName: "OpenAI",
    description: "GPT-Image-1, DALL-E 3 & 2 — Best image quality and instruction following",
    baseUrl: "https://api.openai.com/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "sk-...",
    icon: "openai",
    color: "#10a37f",
    website: "https://platform.openai.com",
    sortOrder: 1,
  },
  {
    name: "stability",
    displayName: "Stability AI",
    description: "Stable Diffusion 3.5, SDXL, inpainting, upscaling, and style control",
    baseUrl: "https://api.stability.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "sk-...",
    icon: "stability",
    color: "#7c3aed",
    website: "https://platform.stability.ai",
    sortOrder: 2,
  },
  {
    name: "replicate",
    displayName: "Replicate",
    description: "Flux, SD, and hundreds of open-source models — huge catalog",
    baseUrl: "https://api.replicate.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "r8_...",
    icon: "replicate",
    color: "#a855f7",
    website: "https://replicate.com",
    sortOrder: 3,
  },
  {
    name: "fal",
    displayName: "Fal.ai",
    description: "Flux, SD, Ideogram, Kling, Pika, Wan — widest model selection with async queue",
    baseUrl: "https://queue.fal.run",
    authHeader: "Authorization",
    authPrefix: "Key",
    keyFormat: "fal-key",
    icon: "fal",
    color: "#6366f1",
    website: "https://fal.ai",
    sortOrder: 4,
  },
  {
    name: "together",
    displayName: "Together AI",
    description: "FLUX models (FREE Schnell), SDXL, Ideogram — OpenAI-compatible API",
    baseUrl: "https://api.together.xyz",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "together-key",
    icon: "together",
    color: "#06b6d4",
    website: "https://together.ai",
    sortOrder: 5,
  },
  {
    name: "fireworks",
    displayName: "Fireworks AI",
    description: "FLUX Schnell/Dev, SDXL — fast inference, OpenAI-compatible API",
    baseUrl: "https://api.fireworks.ai/inference",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "fireworks-key",
    icon: "fireworks",
    color: "#f97316",
    website: "https://fireworks.ai",
    sortOrder: 6,
  },
  {
    name: "ideogram",
    displayName: "Ideogram",
    description: "Ideogram 3.0 — Best text rendering in images, great quality",
    baseUrl: "https://api.ideogram.ai",
    authHeader: "Api-Key",
    authPrefix: "",
    keyFormat: "ideogram-key",
    icon: "ideogram",
    color: "#ec4899",
    website: "https://developer.ideogram.ai",
    sortOrder: 7,
  },
  {
    name: "google",
    displayName: "Google AI Studio (Legacy)",
    description: "Legacy provider — use Google AI Studio or Google Vertex AI instead",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authHeader: "x-goog-api-key",
    authPrefix: "",
    keyFormat: "AIza...",
    icon: "google",
    color: "#4285f4",
    website: "https://aistudio.google.com",
    sortOrder: 8,
    isActive: false,
  },
  {
    name: "google-aistudio",
    displayName: "Google AI Studio",
    description: "Gemini + Imagen models via API key — for individual developers",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authHeader: "x-goog-api-key",
    authPrefix: "",
    keyFormat: "AIza...",
    icon: "google-aistudio",
    color: "#4285f4",
    website: "https://aistudio.google.com/api-keys",
    sortOrder: 8,
  },
  {
    name: "google-vertex",
    displayName: "Google Vertex AI",
    description: "Enterprise-grade Imagen & Veo via Vertex AI — service account or OAuth2 authentication",
    baseUrl: "https://us-central1-aiplatform.googleapis.com/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "service-account JSON or OAuth2 token",
    icon: "google-vertex",
    color: "#34a853",
    website: "https://console.cloud.google.com/vertex-ai",
    sortOrder: 17,
  },
  {
    name: "runway",
    displayName: "Runway",
    description: "Gen-4 Turbo — Best-in-class video generation with flexible duration",
    baseUrl: "https://api.dev.runwayml.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "runway-key",
    icon: "runway",
    color: "#22c55e",
    website: "https://dev.runwayml.com",
    sortOrder: 9,
  },
  {
    name: "luma",
    displayName: "Luma AI",
    description: "Ray2 — High quality video generation with low latency",
    baseUrl: "https://api.lumalabs.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "luma-key",
    icon: "luma",
    color: "#8b5cf6",
    website: "https://lumalabs.ai",
    sortOrder: 10,
  },
  {
    name: "huggingface",
    displayName: "Hugging Face",
    description: "Free tier access to FLUX, SD, and hundreds of open models",
    baseUrl: "https://api-inference.huggingface.co/models",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "hf_...",
    icon: "huggingface",
    color: "#ffd21e",
    website: "https://huggingface.co",
    sortOrder: 11,
  },
  {
    name: "leonardo",
    displayName: "Leonardo.ai",
    description: "Phoenix, Kino XL, Vision XL — cinematic and photorealistic images",
    baseUrl: "https://cloud.leonardo.ai/api/rest/v1",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "leonardo-key",
    icon: "leonardo",
    color: "#a855f7",
    website: "https://leonardo.ai",
    sortOrder: 12,
  },
  {
    name: "recraft",
    displayName: "Recraft AI",
    description: "Recraft V3 — Vector + raster, style control, long text support",
    baseUrl: "https://api.recraft.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "recraft-key",
    icon: "recraft",
    color: "#14b8a6",
    website: "https://recraft.ai",
    sortOrder: 13,
  },
  {
    name: "bfl",
    displayName: "Black Forest Labs",
    description: "FLUX Pro, Kontext — Direct API from the FLUX creators",
    baseUrl: "https://api.bfl.ml",
    authHeader: "X-Key",
    authPrefix: "",
    keyFormat: "bfl-key",
    icon: "bfl",
    color: "#ef4444",
    website: "https://bfl.dev",
    sortOrder: 14,
  },
  {
    name: "aimlapi",
    displayName: "AI/ML API",
    description: "400+ models aggregator — OpenAI-compatible, free tier available",
    baseUrl: "https://api.aimlapi.com",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "aiml-key",
    icon: "aimlapi",
    color: "#f59e0b",
    website: "https://aimlapi.com",
    sortOrder: 15,
  },
  {
    name: "seedance",
    displayName: "Seedance (ByteDance)",
    description: "Seedance 2.0 — High quality video generation with cinematic workflows",
    baseUrl: "https://api.seedance.ai",
    authHeader: "Authorization",
    authPrefix: "Bearer",
    keyFormat: "seedance-key",
    icon: "seedance",
    color: "#00d4aa",
    website: "https://seedance.ai",
    sortOrder: 16,
  },
];

export const MODELS = [
  // OpenAI
  {
    providerName: "openai",
    name: "GPT Image 1",
    modelId: "gpt-image-1",
    type: "image",
    capabilities: "t2i,i2i,edit,inpaint",
    description: "Best image quality, great instruction following. Supports text-to-image, image editing, and inpainting.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.04–0.167/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "openai",
    name: "DALL-E 3",
    modelId: "dall-e-3",
    type: "image",
    capabilities: "t2i",
    description: "High quality text-to-image with vivid and natural styles.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "standard", style: "vivid", n: 1 }),
    priceInfo: "$0.04–0.08/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "openai",
    name: "GPT Image 2",
    modelId: "gpt-image-2",
    type: "image",
    capabilities: "t2i,edit,inpaint",
    description: "Latest GPT Image 2 with text rendering, multi-reference editing, and character consistency. Supports edits endpoint.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.04–0.167/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "openai",
    name: "ChatGPT 4o Image",
    modelId: "chatgpt-4o-image",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "ChatGPT 4o's native image generation with superior instruction following.",
    defaultParams: JSON.stringify({ size: "1024x1024", quality: "auto", n: 1 }),
    priceInfo: "~$0.02–0.08/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "openai",
    name: "DALL-E 2",
    modelId: "dall-e-2",
    type: "image",
    capabilities: "t2i,edit,variations",
    description: "Legacy model with editing and variation support.",
    defaultParams: JSON.stringify({ size: "1024x1024", n: 1 }),
    priceInfo: "$0.016–0.020/image",
    isDefault: false,
    sortOrder: 3,
  },

  // Stability AI
  {
    providerName: "stability",
    name: "Stable Image Ultra",
    modelId: "stable-image-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Highest quality text-to-image generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "stability",
    name: "SD 3.5 Large",
    modelId: "stable-diffusion-3.5-large",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 3.5 Large — high quality open-source model.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.065/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "stability",
    name: "SD 3.5 Large Turbo",
    modelId: "stable-diffusion-3.5-large-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Faster version of SD 3.5 Large.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "stability",
    name: "Stable Image Core",
    modelId: "stable-image-core",
    type: "image",
    capabilities: "t2i",
    description: "Fast text-to-image generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "stability",
    name: "SDXL 1.0",
    modelId: "sdxl-1.0",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion XL — popular open model.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "stability",
    name: "Creative Upscale",
    modelId: "creative-upscale",
    type: "image",
    capabilities: "upscale",
    description: "4x creative upscaling with detail enhancement.",
    defaultParams: JSON.stringify({ output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "stability",
    name: "Erase/Inpaint",
    modelId: "stable-image-erase",
    type: "image",
    capabilities: "inpaint",
    description: "Remove objects or inpaint masked areas.",
    defaultParams: JSON.stringify({ output_format: "png" }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "stability",
    name: "SD 4",
    modelId: "stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 — latest generation with superior quality and prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 8,
  },
  {
    providerName: "stability",
    name: "SD 3.5 Medium",
    modelId: "stable-diffusion-3.5-medium",
    type: "image",
    capabilities: "t2i",
    description: "SD 3.5 Medium — balanced quality and speed",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", output_format: "png" }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },

  // Replicate
  {
    providerName: "replicate",
    name: "FLUX 1.1 Pro",
    modelId: "black-forest-labs/flux-1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "Best open-ish model, excellent quality.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "replicate",
    name: "FLUX Dev",
    modelId: "black-forest-labs/flux-dev",
    type: "image",
    capabilities: "t2i",
    description: "Great quality/cost ratio, open weights.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "replicate",
    name: "FLUX Schnell",
    modelId: "black-forest-labs/flux-schnell",
    type: "image",
    capabilities: "t2i",
    description: "Fastest FLUX model, very cheap.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1, num_inference_steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "replicate",
    name: "FLUX Kontext Pro",
    modelId: "black-forest-labs/flux-kontext-pro",
    type: "image",
    capabilities: "edit,inpaint",
    description: "Image editing and inpainting with FLUX.",
    defaultParams: JSON.stringify({ num_outputs: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "replicate",
    name: "Ideogram v3",
    modelId: "ideogram-ai/ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering in images.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1" }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "replicate",
    name: "SD 4",
    modelId: "stability-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Latest Stable Diffusion 4 via Replicate",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "replicate",
    name: "FLUX 2 Pro",
    modelId: "black-forest-labs/flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 Pro with superior quality and text rendering",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "replicate",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev, open weights with improved quality",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 8,
  },
  {
    providerName: "replicate",
    name: "Seedream 4.0",
    modelId: "bytedance/seedream-4",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.0 — unified generation and editing, up to 4MP",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },
  {
    providerName: "replicate",
    name: "Seedream 4.5",
    modelId: "bytedance/seedream-4.5",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 — improved multi-image editing, accurate subject ID",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 10,
  },
  {
    providerName: "replicate",
    name: "Nano Banana 2",
    modelId: "google/nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 — Pro-level quality with lightning speed",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 11,
  },
  {
    providerName: "replicate",
    name: "Recraft V3",
    modelId: "recraft-ai/recraft-v3",
    type: "image",
    capabilities: "t2i",
    description: "Vector + raster with long text and precise positioning",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 12,
  },
  {
    providerName: "replicate",
    name: "Playground v3",
    modelId: "playgroundai/playground-v3",
    type: "image",
    capabilities: "t2i",
    description: "Playground v3 — great for creative and commercial work",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", num_outputs: 1 }),
    priceInfo: "~$0.03/image",
    isDefault: false,
    sortOrder: 13,
  },
  {
    providerName: "replicate",
    name: "Seedance 2.0 Video",
    modelId: "bytedance/seedance-2.0",
    type: "video",
    capabilities: "t2v,i2v",
    description: "ByteDance Seedance 2.0 cinematic video generation",
    defaultParams: JSON.stringify({ duration: 5 }),
    priceInfo: "Per-second",
    isDefault: false,
    sortOrder: 14,
  },

  // Fal.ai
  {
    providerName: "fal",
    name: "FLUX Pro v1.1",
    modelId: "fal-ai/flux-pro/v1.1",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via Fal.ai — top quality.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "fal",
    name: "FLUX Dev",
    modelId: "fal-ai/flux/dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Fal.ai.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "fal",
    name: "FLUX Schnell",
    modelId: "fal-ai/flux/schnell",
    type: "image",
    capabilities: "t2i",
    description: "Fastest FLUX via Fal.ai.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1, num_inference_steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "fal",
    name: "FLUX Kontext Pro",
    modelId: "fal-ai/flux-kontext-pro",
    type: "image",
    capabilities: "edit",
    description: "Image editing with FLUX Kontext.",
    defaultParams: JSON.stringify({ num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "fal",
    name: "FLUX Realism",
    modelId: "fal-ai/flux-realism",
    type: "image",
    capabilities: "t2i",
    description: "Realistic photo generation with FLUX.",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "fal",
    name: "FLUX 2 Pro",
    modelId: "fal-ai/flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 with superior quality and text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "fal",
    name: "FLUX 2 Dev",
    modelId: "fal-ai/flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev, improved over v1",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "fal",
    name: "Ideogram v3",
    modelId: "fal-ai/ideogram/v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering via Fal.ai",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 8,
  },
  {
    providerName: "fal",
    name: "SD 4",
    modelId: "fal-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Fal.ai",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 9,
  },
  {
    providerName: "fal",
    name: "FLUX 2 Dev Turbo",
    modelId: "fal-ai/flux-2-dev-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Fal's distilled FLUX 2 Dev — 10x cheaper, 6x more efficient",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.01/image",
    isDefault: false,
    sortOrder: 10,
  },
  {
    providerName: "fal",
    name: "Seedream 4.0",
    modelId: "fal-ai/bytedance/seedream/v4/text-to-image",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.0 via Fal — generation + editing in one model",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 11,
  },
  {
    providerName: "fal",
    name: "Seedream 4.5",
    modelId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 via Fal — improved editing accuracy",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 12,
  },
  {
    providerName: "fal",
    name: "FLUX 1.1 Pro Ultra",
    modelId: "fal-ai/flux/v1.1-pro-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Ultra-high quality FLUX Pro variant with enhanced detail",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 13,
  },
  {
    providerName: "fal",
    name: "FLUX Anime",
    modelId: "fal-ai/flux/anime",
    type: "image",
    capabilities: "t2i",
    description: "Anime-optimized FLUX model for illustration and manga styles",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.025/image",
    isDefault: false,
    sortOrder: 14,
  },
  {
    providerName: "fal",
    name: "FLUX 2 Pro Ultra",
    modelId: "fal-ai/flux-2-pro-ultra",
    type: "image",
    capabilities: "t2i",
    description: "Highest quality FLUX 2 variant with maximum detail and text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.12/image",
    isDefault: false,
    sortOrder: 15,
  },
  {
    providerName: "fal",
    name: "Imagen 4",
    modelId: "fal-ai/google/imagen4",
    type: "image",
    capabilities: "t2i",
    description: "Google Imagen 4 via Fal — photorealistic with excellent text rendering",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: false,
    sortOrder: 16,
  },
  {
    providerName: "fal",
    name: "Kandinsky 3.1",
    modelId: "fal-ai/kandinsky-3.1",
    type: "image",
    capabilities: "t2i",
    description: "Kandinsky 3.1 — popular Russian open model with vibrant colors",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 17,
  },
  {
    providerName: "fal",
    name: "Nano Banana 2",
    modelId: "fal-ai/google/nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google Nano Banana 2 via Fal — Pro-level quality at speed",
    defaultParams: JSON.stringify({ image_size: "landscape_16_9", num_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 18,
  },
  {
    providerName: "fal",
    name: "Pika 2.2",
    modelId: "fal-ai/pika",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Creative video generation with Pikaffects and Pikaswaps.",
    defaultParams: JSON.stringify({ duration: "5" }),
    priceInfo: "Per-video via Fal",
    isDefault: true,
    sortOrder: 10,
  },
  {
    providerName: "fal",
    name: "Kling Video v1",
    modelId: "fal-ai/kling-video/v1/standard",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Kling AI video generation via Fal.",
    defaultParams: JSON.stringify({ duration: "5" }),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 11,
  },
  {
    providerName: "fal",
    name: "MiniMax Video",
    modelId: "fal-ai/minimax/video-01-live",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Hailuo/MiniMax video generation via Fal.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 12,
  },
  {
    providerName: "fal",
    name: "Wan v2.1 Text-to-Video",
    modelId: "fal-ai/wan/v2.1/text-to-video",
    type: "video",
    capabilities: "t2v",
    description: "Wan open-weight video generation via Fal.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 13,
  },

  // Together AI
  {
    providerName: "together",
    name: "FLUX Schnell (FREE)",
    modelId: "black-forest-labs/FLUX.1-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FREE FLUX Schnell — fastest, decent quality, zero cost!",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "FREE",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "together",
    name: "FLUX Dev",
    modelId: "black-forest-labs/FLUX.1-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.003–0.018/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "together",
    name: "FLUX 1.1 Pro",
    modelId: "black-forest-labs/FLUX.1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "together",
    name: "FLUX Fill (Inpainting)",
    modelId: "black-forest-labs/FLUX.1-fill",
    type: "image",
    capabilities: "inpaint",
    description: "Inpainting with FLUX via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "together",
    name: "FLUX Canny",
    modelId: "black-forest-labs/FLUX.1-canny",
    type: "image",
    capabilities: "i2i",
    description: "Canny edge control with FLUX.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "together",
    name: "FLUX Depth",
    modelId: "black-forest-labs/FLUX.1-depth",
    type: "image",
    capabilities: "i2i",
    description: "Depth control with FLUX.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "together",
    name: "SD 4",
    modelId: "stability-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "together",
    name: "FLUX 2 Pro",
    modelId: "black-forest-labs/FLUX.2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 Pro via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 8,
  },
  {
    providerName: "together",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev open weights via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },
  {
    providerName: "together",
    name: "Ideogram v3",
    modelId: "ideogram-ai/ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering in images via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 10,
  },
  {
    providerName: "together",
    name: "SDXL 1.0",
    modelId: "stabilityai/stable-diffusion-xl-base-1.0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL with massive LoRA ecosystem via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.002/image",
    isDefault: false,
    sortOrder: 11,
  },

  // Fireworks AI
  {
    providerName: "fireworks",
    name: "FLUX Schnell FP8",
    modelId: "FLUX.1-schnell-fp8",
    type: "image",
    capabilities: "t2i",
    description: "Fast FLUX Schnell on Fireworks.",
    defaultParams: JSON.stringify({ n: 1, cfg_scale: 3, steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "fireworks",
    name: "FLUX Dev FP8",
    modelId: "FLUX.1-dev-fp8",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev on Fireworks.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.015/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "fireworks",
    name: "SDXL 1.0",
    modelId: "stable-diffusion-xl-1024-v1-0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL on Fireworks.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.002/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "fireworks",
    name: "FLUX 2 Pro",
    modelId: "FLUX.2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro on Fireworks",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "fireworks",
    name: "FLUX 2 Dev",
    modelId: "FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev on Fireworks, improved quality",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "fireworks",
    name: "SDXL Lightning",
    modelId: "bytedance/sdxl-lightning-4step",
    type: "image",
    capabilities: "t2i",
    description: "ByteDance's ultra-fast SDXL variant, 4 steps",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.001/image",
    isDefault: false,
    sortOrder: 6,
  },

  // Ideogram
  {
    providerName: "ideogram",
    name: "Ideogram 3.0",
    modelId: "ideogram-3.0",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering, high quality generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.08/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "ideogram",
    name: "Ideogram 3.0 Flash",
    modelId: "ideogram-3.0-flash",
    type: "image",
    capabilities: "t2i",
    description: "Faster, lower cost version of Ideogram 3.0.",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.04/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "ideogram",
    name: "Ideogram 2a Turbo",
    modelId: "ideogram-2a-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Fast Ideogram 2a with good text rendering, budget-friendly",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.02/image",
    isDefault: false,
    sortOrder: 3,
  },

  // Google
  {
    providerName: "google",
    name: "Imagen 4",
    modelId: "imagen-4.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest quality image model.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.10–0.20/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "google",
    name: "Imagen 4 Fast",
    modelId: "imagen-4.0-fast-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Faster Imagen 4 generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.02–0.05/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "google",
    name: "Imagen 3",
    modelId: "imagen-3.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Previous generation Imagen.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04–0.067/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "google",
    name: "Imagen 4 Ultra",
    modelId: "imagen-4.0-ultra-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest-fidelity Imagen — precise prompt adherence, photorealistic",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.15–0.30/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "google",
    name: "Nano Banana 2",
    modelId: "nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 — combines Pro quality with speed",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "google",
    name: "Veo 2",
    modelId: "veo-2.0-generate-001",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Google Veo 2 — high quality video generation via Google AI Studio",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.50/video",
    isDefault: false,
    sortOrder: 6,
  },

  // Google AI Studio
  {
    providerName: "google-aistudio",
    name: "Gemini 2.5 Flash Image",
    modelId: "gemini-2.5-flash-preview-05-20",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "100% FREE — Gemini 2.5 Flash with native image generation & editing. Conversational create & edit.",
    defaultParams: JSON.stringify({ number_of_images: 1 }),
    priceInfo: "FREE",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 4",
    modelId: "imagen-4.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest quality image model via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 4 Fast",
    modelId: "imagen-4.0-fast-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Faster Imagen 4 generation via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 3",
    modelId: "imagen-3.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Previous generation Imagen via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 4 Ultra",
    modelId: "imagen-4.0-ultra-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest-fidelity Imagen via AI Studio — precise prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.15/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "google-aistudio",
    name: "Nano Banana 2",
    modelId: "nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 — combines Pro quality with speed via AI Studio",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "google-aistudio",
    name: "Veo 2",
    modelId: "veo-2.0-generate-001",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Google Veo 2 — high quality video generation via AI Studio",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.50/video",
    isDefault: true,
    sortOrder: 7,
  },

  // Google Vertex AI
  {
    providerName: "google-vertex",
    name: "Imagen 4",
    modelId: "imagen-4.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest quality image model via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 4 Fast",
    modelId: "imagen-4.0-fast-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Faster Imagen 4 generation via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 3",
    modelId: "imagen-3.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Previous generation Imagen via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 4 Ultra",
    modelId: "imagen-4.0-ultra-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest-fidelity Imagen via Vertex AI — precise prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.15/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "google-vertex",
    name: "Veo 2",
    modelId: "veo-2.0-generate-001",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Google Veo 2 — enterprise video generation via Vertex AI",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.50/video",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "google-vertex",
    name: "Gemini 2.5 Flash Image",
    modelId: "gemini-2.5-flash-preview-05-20",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "FREE — Gemini 2.5 Flash with native image generation & editing via Vertex AI",
    defaultParams: JSON.stringify({ number_of_images: 1 }),
    priceInfo: "FREE",
    isDefault: false,
    sortOrder: 6,
  },

  // Runway
  {
    providerName: "runway",
    name: "Gen-4 Turbo",
    modelId: "gen4-turbo",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Best-in-class video generation with flexible 2-10s duration.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "runway",
    name: "Gen-4",
    modelId: "gen4",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Runway Gen-4 video generation.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "runway",
    name: "Gen-3 Alpha Turbo",
    modelId: "gen3a_turbo",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Previous generation, still excellent quality.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: false,
    sortOrder: 3,
  },

  // Luma AI
  {
    providerName: "luma",
    name: "Ray2",
    modelId: "ray2",
    type: "video",
    capabilities: "t2v,i2v",
    description: "High quality video with low latency.",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.20–0.30/sec",
    isDefault: true,
    sortOrder: 1,
  },

  // Hugging Face
  {
    providerName: "huggingface",
    name: "FLUX.1 Dev",
    modelId: "black-forest-labs/FLUX.1-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "huggingface",
    name: "FLUX.1 Schnell",
    modelId: "black-forest-labs/FLUX.1-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Schnell via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "huggingface",
    name: "SDXL Base 1.0",
    modelId: "stabilityai/stable-diffusion-xl-base-1.0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "huggingface",
    name: "SD 3.5 Large",
    modelId: "stabilityai/stable-diffusion-3.5-large",
    type: "image",
    capabilities: "t2i",
    description: "SD 3.5 Large via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "huggingface",
    name: "SD 4",
    modelId: "stabilityai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Hugging Face",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "huggingface",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev via Hugging Face Inference API",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "huggingface",
    name: "Kandinsky 3.1",
    modelId: "ai-forever/kandinsky-3.1",
    type: "image",
    capabilities: "t2i",
    description: "Kandinsky 3.1 — vibrant open model via Hugging Face",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "huggingface",
    name: "SDXL Lightning",
    modelId: "bytedance/sdxl-lightning-4step",
    type: "image",
    capabilities: "t2i",
    description: "Ultra-fast SDXL Lightning by ByteDance",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 8,
  },

  // Leonardo.ai
  {
    providerName: "leonardo",
    name: "Phoenix",
    modelId: "phoenix",
    type: "image",
    capabilities: "t2i",
    description: "Leonardo's flagship model with Alchemy v4.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "leonardo",
    name: "Leonardo Kino XL",
    modelId: "leonardo-kino-xl",
    type: "image",
    capabilities: "t2i",
    description: "Cinematic image generation.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "leonardo",
    name: "Phoenix 2.0",
    modelId: "phoenix-2.0",
    type: "image",
    capabilities: "t2i,edit",
    description: "Leonardo's next-gen Phoenix 2.0 with improved prompt adherence and text",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "leonardo",
    name: "Leonardo Vision XL",
    modelId: "leonardo-vision-xl",
    type: "image",
    capabilities: "t2i,i2i",
    description: "Vision XL — great for photorealistic and detailed work",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 4,
  },

  // Recraft
  {
    providerName: "recraft",
    name: "Recraft V3",
    modelId: "recraft-v3",
    type: "image",
    capabilities: "t2i",
    description: "Vector + raster generation, style control, long text.",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.02/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "recraft",
    name: "Recraft V3 Vector",
    modelId: "recraft-v3-vector",
    type: "image",
    capabilities: "t2i",
    description: "Vector output with Recraft V3 — SVG and vector art generation",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 2,
  },

  // BFL Direct
  {
    providerName: "bfl",
    name: "FLUX Pro 1.1",
    modelId: "flux-pro-1.1",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro direct from Black Forest Labs.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "bfl",
    name: "FLUX Dev",
    modelId: "flux-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev direct from Black Forest Labs.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.030/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "bfl",
    name: "FLUX Kontext Pro",
    modelId: "flux-kontext-pro",
    type: "image",
    capabilities: "edit",
    description: "Image editing with FLUX Kontext from BFL.",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "bfl",
    name: "FLUX 2 Pro",
    modelId: "flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro direct from BFL — next-gen quality",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "bfl",
    name: "FLUX 2 Dev",
    modelId: "flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev direct from BFL — open weights",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "bfl",
    name: "FLUX Kontext Max",
    modelId: "flux-kontext-max",
    type: "image",
    capabilities: "edit,inpaint",
    description: "Maximum quality FLUX Kontext editing from BFL",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },

  // AI/ML API
  {
    providerName: "aimlapi",
    name: "FLUX 1.1 Pro",
    modelId: "flux-1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via AI/ML API aggregator.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "aimlapi",
    name: "DALL-E 3",
    modelId: "dall-e-3",
    type: "image",
    capabilities: "t2i",
    description: "DALL-E 3 via AI/ML API.",
    defaultParams: JSON.stringify({ n: 1, size: "1024x1024" }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "aimlapi",
    name: "FLUX Schnell",
    modelId: "flux-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Schnell via AI/ML API.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "aimlapi",
    name: "SD 4",
    modelId: "stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "aimlapi",
    name: "GPT Image 2",
    modelId: "gpt-image-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "GPT Image 2 via AI/ML API aggregator",
    defaultParams: JSON.stringify({ n: 1, size: "1024x1024" }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 5,
  },
  {
    providerName: "aimlapi",
    name: "Ideogram v3",
    modelId: "ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 6,
  },
  {
    providerName: "aimlapi",
    name: "Nano Banana 2",
    modelId: "nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 7,
  },
  {
    providerName: "aimlapi",
    name: "Seedream 4.5",
    modelId: "seedream-4.5",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 8,
  },
  {
    providerName: "aimlapi",
    name: "FLUX 2 Pro",
    modelId: "flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro via AI/ML API aggregator",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 9,
  },
  {
    providerName: "aimlapi",
    name: "Imagen 4",
    modelId: "imagen-4",
    type: "image",
    capabilities: "t2i",
    description: "Google Imagen 4 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 10,
  },

  // Seedance (ByteDance)
  {
    providerName: "seedance",
    name: "Seedance 2.0",
    modelId: "seedance-2.0",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Cinematic AI video generation by ByteDance",
    defaultParams: JSON.stringify({ duration: 5, aspect_ratio: "16:9" }),
    priceInfo: "Per-second",
    isDefault: true,
    sortOrder: 1,
  },
];
