// Video model definitions for seeding the database
export const VIDEO_MODELS = [
  {
    providerName: "replicate",
    name: "Seedance 2.0 Video",
    modelId: "bytedance/seedance-2.0",
    type: "video",
    capabilities: "t2v,i2v",
    description: "ByteDance Seedance 2.0 cinematic video generation",
    defaultParams: JSON.stringify({ duration: 5 }),
    priceInfo: "Per-second",
    isDefault: false,
    sortOrder: 14,
  },

  {
    providerName: "fal",
    name: "Pika 2.2",
    modelId: "fal-ai/pika",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Creative video generation with Pikaffects and Pikaswaps.",
    defaultParams: JSON.stringify({ duration: "5" }),
    priceInfo: "Per-video via Fal",
    isDefault: true,
    sortOrder: 10,
  },

  {
    providerName: "fal",
    name: "Kling Video v1",
    modelId: "fal-ai/kling-video/v1/standard",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Kling AI video generation via Fal.",
    defaultParams: JSON.stringify({ duration: "5" }),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 11,
  },

  {
    providerName: "fal",
    name: "MiniMax Video",
    modelId: "fal-ai/minimax/video-01-live",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Hailuo/MiniMax video generation via Fal.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 12,
  },

  {
    providerName: "fal",
    name: "Wan v2.1 Text-to-Video",
    modelId: "fal-ai/wan/v2.1/text-to-video",
    type: "video",
    capabilities: "t2v",
    description: "Wan open-weight video generation via Fal.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Per-second via Fal",
    isDefault: false,
    sortOrder: 13,
  },

  {
    providerName: "runway",
    name: "Gen-4 Turbo",
    modelId: "gen4-turbo",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Best-in-class video generation with flexible 2-10s duration.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "runway",
    name: "Gen-4",
    modelId: "gen4",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Runway Gen-4 video generation.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "runway",
    name: "Gen-3 Alpha Turbo",
    modelId: "gen3a_turbo",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Previous generation, still excellent quality.",
    defaultParams: JSON.stringify({ duration: 5, ratio: "16:9" }),
    priceInfo: "$0.05/sec",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "luma",
    name: "Ray2",
    modelId: "ray2",
    type: "video",
    capabilities: "t2v,i2v",
    description: "High quality video with low latency.",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.20–0.30/sec",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "seedance",
    name: "Seedance 2.0",
    modelId: "seedance-2.0",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Cinematic AI video generation by ByteDance",
    defaultParams: JSON.stringify({ duration: 5, aspect_ratio: "16:9" }),
    priceInfo: "Per-second",
    isDefault: true,
    sortOrder: 1,
  },

  // Google AI Studio video models
  {
    providerName: "google-aistudio",
    name: "Veo 2",
    modelId: "veo-2.0-generate-001",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Google Veo 2 — high quality video generation via AI Studio",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.50/video",
    isDefault: true,
    sortOrder: 1,
  },

  // Google Vertex AI video models
  {
    providerName: "google-vertex",
    name: "Veo 2",
    modelId: "veo-2.0-generate-001",
    type: "video",
    capabilities: "t2v,i2v",
    description: "Google Veo 2 — enterprise video generation via Vertex AI",
    defaultParams: JSON.stringify({ aspect_ratio: "16:9" }),
    priceInfo: "~$0.50/video",
    isDefault: true,
    sortOrder: 1,
  },
];
