// Image model definitions (Part 2: Together, Fireworks, Ideogram, Google, HuggingFace, Leonardo, Recraft, BFL, AI/ML API)
export const IMAGE_MODELS = [
  {
    providerName: "together",
    name: "FLUX Schnell (FREE)",
    modelId: "black-forest-labs/FLUX.1-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FREE FLUX Schnell — fastest, decent quality, zero cost!",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "FREE",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "together",
    name: "FLUX Dev",
    modelId: "black-forest-labs/FLUX.1-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.003–0.018/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "together",
    name: "FLUX 1.1 Pro",
    modelId: "black-forest-labs/FLUX.1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "together",
    name: "FLUX Fill (Inpainting)",
    modelId: "black-forest-labs/FLUX.1-fill",
    type: "image",
    capabilities: "inpaint",
    description: "Inpainting with FLUX via Together AI.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "together",
    name: "FLUX Canny",
    modelId: "black-forest-labs/FLUX.1-canny",
    type: "image",
    capabilities: "i2i",
    description: "Canny edge control with FLUX.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "together",
    name: "FLUX Depth",
    modelId: "black-forest-labs/FLUX.1-depth",
    type: "image",
    capabilities: "i2i",
    description: "Depth control with FLUX.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.018/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "together",
    name: "SD 4",
    modelId: "stability-ai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "together",
    name: "FLUX 2 Pro",
    modelId: "black-forest-labs/FLUX.2-pro",
    type: "image",
    capabilities: "t2i",
    description: "Next-gen FLUX 2 Pro via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "together",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev open weights via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 9,
  },

  {
    providerName: "together",
    name: "Ideogram v3",
    modelId: "ideogram-ai/ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering in images via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.06/image",
    isDefault: false,
    sortOrder: 10,
  },

  {
    providerName: "together",
    name: "SDXL 1.0",
    modelId: "stabilityai/stable-diffusion-xl-base-1.0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL with massive LoRA ecosystem via Together AI",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, n: 1 }),
    priceInfo: "~$0.002/image",
    isDefault: false,
    sortOrder: 11,
  },

  {
    providerName: "fireworks",
    name: "FLUX Schnell FP8",
    modelId: "FLUX.1-schnell-fp8",
    type: "image",
    capabilities: "t2i",
    description: "Fast FLUX Schnell on Fireworks.",
    defaultParams: JSON.stringify({ n: 1, cfg_scale: 3, steps: 4 }),
    priceInfo: "~$0.003/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "fireworks",
    name: "FLUX Dev FP8",
    modelId: "FLUX.1-dev-fp8",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev on Fireworks.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.015/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "fireworks",
    name: "SDXL 1.0",
    modelId: "stable-diffusion-xl-1024-v1-0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL on Fireworks.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.002/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "fireworks",
    name: "FLUX 2 Pro",
    modelId: "FLUX.2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro on Fireworks",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "fireworks",
    name: "FLUX 2 Dev",
    modelId: "FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev on Fireworks, improved quality",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "fireworks",
    name: "SDXL Lightning",
    modelId: "bytedance/sdxl-lightning-4step",
    type: "image",
    capabilities: "t2i",
    description: "ByteDance's ultra-fast SDXL variant, 4 steps",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "~$0.001/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "ideogram",
    name: "Ideogram 3.0",
    modelId: "ideogram-3.0",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering, high quality generation.",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.08/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "ideogram",
    name: "Ideogram 3.0 Flash",
    modelId: "ideogram-3.0-flash",
    type: "image",
    capabilities: "t2i",
    description: "Faster, lower cost version of Ideogram 3.0.",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.04/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "ideogram",
    name: "Ideogram 2a Turbo",
    modelId: "ideogram-2a-turbo",
    type: "image",
    capabilities: "t2i",
    description: "Fast Ideogram 2a with good text rendering, budget-friendly",
    defaultParams: JSON.stringify({ aspect_ratio: "ASPECT_1_1", style_type: "AUTO" }),
    priceInfo: "$0.02/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "google-aistudio",
    name: "Gemini 2.5 Flash Image",
    modelId: "gemini-2.5-flash-preview-image",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "Gemini 2.5 Flash with native image generation & editing (aka nano-banana). Conversational create & edit.",
    defaultParams: JSON.stringify({ number_of_images: 1 }),
    priceInfo: "~$0.039/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "google-aistudio",
    name: "Imagen 4",
    modelId: "imagen-4.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest quality image model via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 4 Fast",
    modelId: "imagen-4.0-fast-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Faster Imagen 4 generation via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 3",
    modelId: "imagen-3.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Previous generation Imagen via AI Studio.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "google-aistudio",
    name: "Imagen 4 Ultra",
    modelId: "imagen-4.0-ultra-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest-fidelity Imagen via AI Studio — precise prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.15/image",
    isDefault: false,
    sortOrder: 5,
  },

  // Google Vertex AI image models
  {
    providerName: "google-vertex",
    name: "Imagen 4",
    modelId: "imagen-4.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest quality image model via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.10/image",
    isDefault: true,
    sortOrder: 1,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 4 Fast",
    modelId: "imagen-4.0-fast-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Faster Imagen 4 generation via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 2,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 3",
    modelId: "imagen-3.0-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Previous generation Imagen via Vertex AI.",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 3,
  },
  {
    providerName: "google-vertex",
    name: "Imagen 4 Ultra",
    modelId: "imagen-4.0-ultra-generate-001",
    type: "image",
    capabilities: "t2i",
    description: "Google's highest-fidelity Imagen via Vertex AI — precise prompt adherence",
    defaultParams: JSON.stringify({ aspect_ratio: "1:1", number_of_images: 1 }),
    priceInfo: "~$0.15/image",
    isDefault: false,
    sortOrder: 4,
  },
  {
    providerName: "google-vertex",
    name: "Gemini 2.5 Flash Image",
    modelId: "gemini-2.5-flash-preview-image",
    type: "image",
    capabilities: "t2i,i2i,edit",
    description: "Gemini 2.5 Flash with native image generation & editing via Vertex AI (aka nano-banana)",
    defaultParams: JSON.stringify({ number_of_images: 1 }),
    priceInfo: "~$0.039/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "huggingface",
    name: "FLUX.1 Dev",
    modelId: "black-forest-labs/FLUX.1-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "huggingface",
    name: "FLUX.1 Schnell",
    modelId: "black-forest-labs/FLUX.1-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Schnell via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "huggingface",
    name: "SDXL Base 1.0",
    modelId: "stabilityai/stable-diffusion-xl-base-1.0",
    type: "image",
    capabilities: "t2i",
    description: "SDXL via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "huggingface",
    name: "SD 3.5 Large",
    modelId: "stabilityai/stable-diffusion-3.5-large",
    type: "image",
    capabilities: "t2i",
    description: "SD 3.5 Large via Hugging Face Inference API.",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "huggingface",
    name: "SD 4",
    modelId: "stabilityai/stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via Hugging Face",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "huggingface",
    name: "FLUX 2 Dev",
    modelId: "black-forest-labs/FLUX.2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev via Hugging Face Inference API",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "huggingface",
    name: "Kandinsky 3.1",
    modelId: "ai-forever/kandinsky-3.1",
    type: "image",
    capabilities: "t2i",
    description: "Kandinsky 3.1 — vibrant open model via Hugging Face",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "huggingface",
    name: "SDXL Lightning",
    modelId: "bytedance/sdxl-lightning-4step",
    type: "image",
    capabilities: "t2i",
    description: "Ultra-fast SDXL Lightning by ByteDance",
    defaultParams: JSON.stringify({}),
    priceInfo: "Free (rate-limited)",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "leonardo",
    name: "Phoenix",
    modelId: "phoenix",
    type: "image",
    capabilities: "t2i",
    description: "Leonardo's flagship model with Alchemy v4.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "leonardo",
    name: "Leonardo Kino XL",
    modelId: "leonardo-kino-xl",
    type: "image",
    capabilities: "t2i",
    description: "Cinematic image generation.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "leonardo",
    name: "Phoenix 2.0",
    modelId: "phoenix-2.0",
    type: "image",
    capabilities: "t2i,edit",
    description: "Leonardo's next-gen Phoenix 2.0 with improved prompt adherence and text",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "leonardo",
    name: "Leonardo Vision XL",
    modelId: "leonardo-vision-xl",
    type: "image",
    capabilities: "t2i,i2i",
    description: "Vision XL — great for photorealistic and detailed work",
    defaultParams: JSON.stringify({ width: 1024, height: 1024, num_images: 1 }),
    priceInfo: "Credit-based",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "recraft",
    name: "Recraft V3",
    modelId: "recraft-v3",
    type: "image",
    capabilities: "t2i",
    description: "Vector + raster generation, style control, long text.",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.02/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "recraft",
    name: "Recraft V3 Vector",
    modelId: "recraft-v3-vector",
    type: "image",
    capabilities: "t2i",
    description: "Vector output with Recraft V3 — SVG and vector art generation",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.02/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "bfl",
    name: "FLUX Pro 1.1",
    modelId: "flux-pro-1.1",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro direct from Black Forest Labs.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.055/image",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "bfl",
    name: "FLUX Dev",
    modelId: "flux-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Dev direct from Black Forest Labs.",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.030/image",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "bfl",
    name: "FLUX Kontext Pro",
    modelId: "flux-kontext-pro",
    type: "image",
    capabilities: "edit",
    description: "Image editing with FLUX Kontext from BFL.",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.055/image",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "bfl",
    name: "FLUX 2 Pro",
    modelId: "flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro direct from BFL — next-gen quality",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "bfl",
    name: "FLUX 2 Dev",
    modelId: "flux-2-dev",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Dev direct from BFL — open weights",
    defaultParams: JSON.stringify({ width: 1024, height: 1024 }),
    priceInfo: "~$0.04/image",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "bfl",
    name: "FLUX Kontext Max",
    modelId: "flux-kontext-max",
    type: "image",
    capabilities: "edit,inpaint",
    description: "Maximum quality FLUX Kontext editing from BFL",
    defaultParams: JSON.stringify({}),
    priceInfo: "~$0.08/image",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "aimlapi",
    name: "FLUX 1.1 Pro",
    modelId: "flux-1.1-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Pro via AI/ML API aggregator.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: true,
    sortOrder: 1,
  },

  {
    providerName: "aimlapi",
    name: "DALL-E 3",
    modelId: "dall-e-3",
    type: "image",
    capabilities: "t2i",
    description: "DALL-E 3 via AI/ML API.",
    defaultParams: JSON.stringify({ n: 1, size: "1024x1024" }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 2,
  },

  {
    providerName: "aimlapi",
    name: "FLUX Schnell",
    modelId: "flux-schnell",
    type: "image",
    capabilities: "t2i",
    description: "FLUX Schnell via AI/ML API.",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 3,
  },

  {
    providerName: "aimlapi",
    name: "SD 4",
    modelId: "stable-diffusion-4",
    type: "image",
    capabilities: "t2i",
    description: "Stable Diffusion 4 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 4,
  },

  {
    providerName: "aimlapi",
    name: "GPT Image 2",
    modelId: "gpt-image-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "GPT Image 2 via AI/ML API aggregator",
    defaultParams: JSON.stringify({ n: 1, size: "1024x1024" }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 5,
  },

  {
    providerName: "aimlapi",
    name: "Ideogram v3",
    modelId: "ideogram-v3",
    type: "image",
    capabilities: "t2i",
    description: "Best text rendering via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 6,
  },

  {
    providerName: "aimlapi",
    name: "Nano Banana 2",
    modelId: "nano-banana-2",
    type: "image",
    capabilities: "t2i,edit",
    description: "Google's Nano Banana 2 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 7,
  },

  {
    providerName: "aimlapi",
    name: "Seedream 4.5",
    modelId: "seedream-4.5",
    type: "image",
    capabilities: "t2i,edit",
    description: "ByteDance Seedream 4.5 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 8,
  },

  {
    providerName: "aimlapi",
    name: "FLUX 2 Pro",
    modelId: "flux-2-pro",
    type: "image",
    capabilities: "t2i",
    description: "FLUX 2 Pro via AI/ML API aggregator",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 9,
  },

  {
    providerName: "aimlapi",
    name: "Imagen 4",
    modelId: "imagen-4",
    type: "image",
    capabilities: "t2i",
    description: "Google Imagen 4 via AI/ML API",
    defaultParams: JSON.stringify({ n: 1 }),
    priceInfo: "Varies",
    isDefault: false,
    sortOrder: 10,
  },
];
