import { NextRequest, NextResponse } from 'next/server';

// Curated prompt templates library — 90+ templates across 25+ categories
const PROMPT_TEMPLATES = [
  // ============ Portrait ============
  {
    id: 'portrait-professional',
    name: 'Professional Headshot',
    description: 'Clean, corporate-style headshot with studio lighting',
    category: 'Portrait',
    prompt: 'A professional headshot portrait of a person, studio lighting, shallow depth of field, 85mm lens, clean background, high detail, corporate style',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'portrait-creative',
    name: 'Creative Portrait',
    description: 'Dramatic fashion portrait with colorful rim light',
    category: 'Portrait',
    prompt: 'A creative portrait with dramatic lighting, colorful rim light, artistic composition, blurred bokeh background, expressive pose, high-end fashion photography',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'portrait-vintage',
    name: 'Vintage Portrait',
    description: 'Retro Hollywood glamour with film grain',
    category: 'Portrait',
    prompt: 'A vintage-style portrait, soft warm lighting, film grain, retro color palette, classic pose, 1940s Hollywood glamour, timeless elegance',
    style: 'Oil Painting',
    aspectRatio: '3:4',
    suggestedStylePreset: 'oil-painting',
    suggestedAspectRatio: '3:4',
  },

  // ============ Landscape ============
  {
    id: 'landscape-mountains',
    name: 'Mountain Vista',
    description: 'Breathtaking alpine mountain landscape at golden hour',
    category: 'Landscape',
    prompt: 'A breathtaking mountain landscape at golden hour, dramatic clouds, snow-capped peaks, reflection in alpine lake, ultra detailed, 8k resolution, National Geographic quality',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'landscape-ocean',
    name: 'Ocean Sunset',
    description: 'Dramatic ocean sunset with crashing waves',
    category: 'Landscape',
    prompt: 'A stunning ocean sunset scene, crashing waves on rocky shore, vibrant orange and purple sky, long exposure water effect, dramatic seascape photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'landscape-aurora',
    name: 'Northern Lights',
    description: 'Spectacular aurora borealis over a frozen lake',
    category: 'Landscape',
    prompt: 'A spectacular aurora borealis display over a frozen lake, vibrant green and purple lights dancing in the night sky, snow-covered pine trees, long exposure photography',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },

  // ============ Product ============
  {
    id: 'product-clean',
    name: 'Clean Product Shot',
    description: 'Professional e-commerce product on white background',
    category: 'Product',
    prompt: 'A professional product photography shot on clean white background, soft studio lighting, commercial quality, sharp focus, no shadows, e-commerce style',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'product-lifestyle',
    name: 'Lifestyle Product',
    description: 'Product in natural setting with warm ambient lighting',
    category: 'Product',
    prompt: 'A lifestyle product photography shot, product in natural setting, warm ambient lighting, shallow depth of field, premium feel, brand storytelling composition',
    style: 'Photorealistic',
    aspectRatio: '4:3',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:3',
  },
  {
    id: 'product-minimal',
    name: 'Minimalist Product',
    description: 'Apple-style product shot on gradient background',
    category: 'Product',
    prompt: 'A minimalist product shot on gradient background, soft directional lighting, clean lines, modern aesthetic, subtle reflections, Apple-style product photography',
    style: '3D Render',
    aspectRatio: '1:1',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '1:1',
  },

  // ============ Abstract ============
  {
    id: 'abstract-fluid',
    name: 'Fluid Dynamics',
    description: 'Swirling colorful fluid dynamics composition',
    category: 'Abstract',
    prompt: 'An abstract fluid dynamics composition, swirling vibrant colors, organic shapes, metallic sheen, marble texture, high contrast, mesmerizing patterns',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'abstract-geometric',
    name: 'Geometric Patterns',
    description: 'Sacred geometry with bold colors and symmetry',
    category: 'Abstract',
    prompt: 'Abstract geometric patterns, sacred geometry, interlocking shapes, bold color palette, mathematical precision, modern art, clean lines and symmetry',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'abstract-ink',
    name: 'Ink in Water',
    description: 'Colorful ink drops dispersing in clear water',
    category: 'Abstract',
    prompt: 'Abstract ink in water photography, colorful ink drops dispersing in clear water, organic flowing shapes, high-speed capture, vibrant color diffusion, macro detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },

  // ============ Fantasy ============
  {
    id: 'fantasy-castle',
    name: 'Enchanted Castle',
    description: 'Epic floating castle with bioluminescent plants',
    category: 'Fantasy',
    prompt: 'An epic enchanted castle on a floating island, magical atmosphere, ethereal lighting, bioluminescent plants, mystical fog, fantasy art, detailed environment',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'fantasy-creature',
    name: 'Mythical Creature',
    description: 'Majestic mythical creature with magical aura',
    category: 'Fantasy',
    prompt: 'A majestic mythical creature in its natural habitat, fantasy illustration, magical aura, dramatic lighting, detailed scales and feathers, epic composition',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fantasy-forest',
    name: 'Mystical Forest',
    description: 'Glowing mushrooms and fairy lights in an enchanted forest',
    category: 'Fantasy',
    prompt: 'A mystical ancient forest with glowing mushrooms and fairy lights, magical atmosphere, volumetric light rays, enchanted pathway, fantasy landscape',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },

  // ============ Sci-Fi ============
  {
    id: 'scifi-city',
    name: 'Cyberpunk City',
    description: 'Neon-lit cyberpunk megacity at night',
    category: 'Sci-Fi',
    prompt: 'A cyberpunk megacity at night, neon signs, flying vehicles, towering skyscrapers, rain-slicked streets, holographic advertisements, Blade Runner inspired',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'scifi-space',
    name: 'Space Station',
    description: 'Massive space station orbiting a ringed planet',
    category: 'Sci-Fi',
    prompt: 'A massive space station orbiting a ringed planet, sci-fi concept art, detailed mechanical structures, solar panels, docking ships, realistic space lighting',
    style: '3D Render',
    aspectRatio: '16:9',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'scifi-robot',
    name: 'Futuristic Robot',
    description: 'Sleek humanoid robot with chrome finish and LED eyes',
    category: 'Sci-Fi',
    prompt: 'A sleek futuristic humanoid robot, chrome and matte black finish, glowing LED eyes, advanced mechanical joints, sci-fi character design, studio lighting',
    style: '3D Render',
    aspectRatio: '3:4',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '3:4',
  },

  // ============ Architecture ============
  {
    id: 'architecture-modern',
    name: 'Modern Building',
    description: 'Clean geometric modern architecture at golden hour',
    category: 'Architecture',
    prompt: 'Modern architectural photography, clean geometric lines, glass and steel facade, dramatic perspective, golden hour lighting, minimalist composition, ultra detailed',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'architecture-interior',
    name: 'Luxury Interior',
    description: 'Luxury open-plan interior with designer furniture',
    category: 'Architecture',
    prompt: 'Luxury modern interior design, open floor plan, floor-to-ceiling windows, designer furniture, warm ambient lighting, architectural photography, wide angle',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'architecture-gothic',
    name: 'Gothic Cathedral',
    description: 'Gothic cathedral interior with stained glass light',
    category: 'Architecture',
    prompt: 'A gothic cathedral interior, soaring vaulted ceilings, stained glass windows casting colorful light, stone columns, religious atmosphere, dramatic perspective',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Food ============
  {
    id: 'food-plated',
    name: 'Gourmet Plating',
    description: 'Fine dining presentation with artistic garnish',
    category: 'Food',
    prompt: 'A beautifully plated gourmet dish, fine dining presentation, micro herbs garnish, artistic sauce drizzle, shallow depth of field, food photography, warm lighting',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'food-bakery',
    name: 'Artisan Bakery',
    description: 'Fresh artisan bread with warm morning light',
    category: 'Food',
    prompt: 'Fresh artisan bread and pastries on a rustic wooden table, flour dusted surface, warm morning light, cozy bakery atmosphere, food styling, appetizing',
    style: 'Photorealistic',
    aspectRatio: '4:3',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:3',
  },
  {
    id: 'food-cocktail',
    name: 'Craft Cocktail',
    description: 'Elegant cocktail with dramatic backlighting',
    category: 'Food',
    prompt: 'A craft cocktail in an elegant glass, condensation droplets, dramatic backlighting, colorful liquid layers, citrus garnish, bar photography, moody atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Fashion ============
  {
    id: 'fashion-editorial',
    name: 'Fashion Editorial',
    description: 'High fashion Vogue-style editorial photography',
    category: 'Fashion',
    prompt: 'High fashion editorial photography, model in designer outfit, dramatic pose, studio lighting, Vogue-style composition, professional retouching, bold fashion statement',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fashion-streetwear',
    name: 'Street Style',
    description: 'Urban street style with city backdrop',
    category: 'Fashion',
    prompt: 'Urban street style fashion photography, trendy outfit, city background, natural lighting, candid pose, contemporary fashion, lifestyle feel',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fashion-runway',
    name: 'Runway Moment',
    description: 'Dramatic haute couture runway moment',
    category: 'Fashion',
    prompt: 'A dramatic runway fashion moment, flowing fabric in motion, dramatic stage lighting, model walking with confidence, haute couture, fashion week atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Animals ============
  {
    id: 'animals-wildlife',
    name: 'Wildlife Close-up',
    description: 'Intense wildlife portrait with telephoto bokeh',
    category: 'Animals',
    prompt: 'A stunning wildlife close-up portrait, intense eyes, detailed fur texture, natural habitat background, National Geographic quality, telephoto lens bokeh',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'animals-pet',
    name: 'Pet Portrait',
    description: 'Adorable pet portrait with soft natural lighting',
    category: 'Animals',
    prompt: 'An adorable pet portrait, soft natural lighting, shallow depth of field, expressive eyes, cozy home environment, heartwarming, professional pet photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'animals-fantasy',
    name: 'Fantasy Animal',
    description: 'Mythical creature with bioluminescent markings',
    category: 'Animals',
    prompt: 'A majestic fantasy creature combining real and mythical animal features, magical aura, bioluminescent markings, enchanted forest setting, detailed illustration',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
  },

  // =====================================================
  // NEW CATEGORIES — Professional Prompt Templates
  // =====================================================

  // ============ E-commerce & Product Photography ============
  {
    id: 'ecommerce-product-hero',
    name: 'Product Hero Shot',
    description: 'Premium product shot with commercial photography style and brand packaging',
    category: 'E-commerce & Product Photography',
    prompt: 'A premium [PRODUCT] product shot on a [SURFACE] surface with [LIGHTING] lighting, shallow depth of field, commercial photography style, [BRAND] packaging visible, clean [COLOR] background, 8K resolution, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, low quality, distorted, watermark, text overlay',
  },
  {
    id: 'ecommerce-miniature-diorama',
    name: 'Miniature Diorama Ad',
    description: 'Tilt-shift miniature product ad with figurine workers',
    category: 'E-commerce & Product Photography',
    prompt: 'A hyper-realistic miniature diorama product advertisement featuring an oversized [PRODUCT] placed on a circular platform, tiny figurine workers climbing scaffolding around the product, tilt-shift miniature aesthetic, studio photography style, soft diffused lighting, clean background, ultra-detailed',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, noisy, deformed, cartoon, low resolution',
  },
  {
    id: 'ecommerce-flat-lay',
    name: 'Flat Lay Product',
    description: 'Premium flat lay advertisement with ingredients/accessories arrangement',
    category: 'E-commerce & Product Photography',
    prompt: 'Ultra-realistic premium [CATEGORY] advertisement, flat lay composition, soft studio lighting, vibrant [COLOR] background, surrounded by [INGREDIENTS/ACCESSORIES], clean modern typography, luxury branding, high-end commercial photography, 8k detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'messy, cluttered, low quality, blurry, distorted',
  },

  // ============ UI & Social Media Mockup ============
  {
    id: 'ui-app-mockup',
    name: 'App UI Mockup',
    description: 'Clean modern mobile app UI with glassmorphism design',
    category: 'UI & Social Media Mockup',
    prompt: 'A clean modern [APP TYPE] mobile app UI mockup, [COLOR SCHEME] color scheme, showing [SCREEN TYPE] screen, glassmorphism design, rounded corners, subtle shadows, SF Pro font style, iOS design language, Dribbble quality',
    style: 'Digital Art',
    aspectRatio: '9:16',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, low quality, unprofessional, cluttered',
  },
  {
    id: 'ui-social-media-post',
    name: 'Social Media Post',
    description: 'Professional social media post design for brand content',
    category: 'UI & Social Media Mockup',
    prompt: 'A professional [PLATFORM] post design for [BRAND], featuring [CONTENT TYPE], modern minimalist layout, [COLOR] accent color, clean typography, eye-catching composition, social media optimized dimensions',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, unprofessional, cluttered, low resolution',
  },
  {
    id: 'ui-dashboard',
    name: 'Dashboard UI',
    description: 'Dark-mode analytics dashboard with glassmorphism cards',
    category: 'UI & Social Media Mockup',
    prompt: 'A dark-mode analytics dashboard UI mockup with [DATA TYPE] charts, sidebar navigation, glassmorphism cards, [ACCENT] accent color, clean data visualization, professional SaaS design, Figma-quality layout',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, low quality, unprofessional, messy layout',
  },

  // ============ Ad Creative & Campaigns ============
  {
    id: 'ad-luxury-product',
    name: 'Luxury Product Ad',
    description: 'Dramatic luxury ad with cinematic light streaks and reflections',
    category: 'Ad Creative & Campaigns',
    prompt: 'A dramatic luxury product advertising image for [PRODUCT] in a dark studio, cinematic [COLOR] and white light streaks, glossy wet ground plane with reflections, ultra-polished commercial photography, high-contrast premium lighting, sleek branding, 8K resolution',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'low quality, blurry, unprofessional, cheap looking, noisy',
  },
  {
    id: 'ad-food-commercial',
    name: 'Food Commercial',
    description: 'Cinematic food hero shot with steam and warm lighting',
    category: 'Ad Creative & Campaigns',
    prompt: 'A cinematic hero image of [FOOD ITEM] on a dark [SURFACE] surface, realistic texture, appetizing steam, warm side light, shallow depth of field, premium food commercial style, no text/logos, 8K',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:5',
    negativePrompt: 'unappetizing, blurry, low quality, distorted, text, watermark, logo',
  },
  {
    id: 'ad-brand-campaign',
    name: 'Brand Campaign Poster',
    description: 'Surreal advertising poster with miniature world inside product',
    category: 'Ad Creative & Campaigns',
    prompt: 'A hyper-detailed surreal advertising poster for [BRAND], deep-toned background in brand color, subject holding [PRODUCT], surreal product moment where product opens into miniature world, octane lighting, 8K sharp foreground',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'low quality, blurry, unprofessional, flat, dull',
  },

  // ============ Infographics & Data Visualization ============
  {
    id: 'infographic-poster',
    name: 'Infographic Poster',
    description: 'Engineering-style modular infographic with icons and data modules',
    category: 'Infographics & Data Visualization',
    prompt: 'An engineering-style infographic poster about [TOPIC], modular structure with arrows and icons, information hierarchy, clean [COLOR] and white color scheme, technical illustration style, bilingual labels, data modules, readable layout',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'realistic photo, blurry, messy, unprofessional, low quality',
  },
  {
    id: 'infographic-process-diagram',
    name: 'Process Diagram',
    description: 'Clean flowchart-style process diagram with connected nodes',
    category: 'Infographics & Data Visualization',
    prompt: 'A clean process diagram showing [PROCESS NAME], flowchart style with connected nodes, [COLOR] accent arrows, modern iconography, step-by-step layout, professional technical illustration, white background',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, cluttered, unprofessional, low quality',
  },

  // ============ Character Design ============
  {
    id: 'character-sheet',
    name: 'Character Sheet',
    description: 'Multi-view character design sheet with costume details and color palette',
    category: 'Character Design',
    prompt: 'A character design sheet for [CHARACTER TYPE], front/side/back views, consistent style, [ART STYLE] art direction, detailed costume design, color palette swatch, character name label, professional concept art quality',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, inconsistent, low quality, messy',
  },
  {
    id: 'character-expression-grid',
    name: 'Expression Grid',
    description: '16-panel expression grid showing multiple emotions',
    category: 'Character Design',
    prompt: 'A 16-panel expression grid of [CHARACTER DESCRIPTION], consistent face shape and hairstyle across all panels, showing emotions: happy, sad, angry, surprised, shy, confused, scared, proud, and more, [ART STYLE] style',
    style: 'Anime',
    aspectRatio: '1:1',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'realistic photo, inconsistent faces, blurry, low quality',
  },
  {
    id: 'character-anime-portrait',
    name: 'Anime Character Portrait',
    description: 'Portrait anime illustration with polished rendering and luminous eyes',
    category: 'Character Design',
    prompt: 'Create a portrait-oriented anime illustration of [CHARACTER], [AGE] years old, [EXPRESSION], wearing [OUTFIT], in [SETTING], polished modern anime rendering, crisp line art, luminous eyes, soft cel shading, [MOOD] atmosphere',
    style: 'Anime',
    aspectRatio: '3:4',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'realistic photo, blurry, deformed, extra limbs, bad anatomy',
  },

  // ============ Architecture & Interior ============
  {
    id: 'arch-render',
    name: 'Architecture Render',
    description: 'Photorealistic architectural visualization with landscape surroundings',
    category: 'Architecture & Interior',
    prompt: 'A photorealistic architectural rendering of [BUILDING TYPE], [STYLE] style, [TIME OF DAY] lighting, landscaped surroundings, glass and [MATERIAL] facade, professional architecture visualization, Unreal Engine quality, 8K',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, cartoon',
  },
  {
    id: 'arch-interior-design',
    name: 'Interior Design',
    description: 'Luxury interior design with natural light and designer furniture',
    category: 'Architecture & Interior',
    prompt: 'A luxury [ROOM TYPE] interior design, [STYLE] style, [COLOR PALETTE] color scheme, natural light through large windows, [FURNITURE] furniture, plants, professional interior photography, Architectural Digest quality, 8K resolution',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, cluttered, unprofessional',
  },

  // ============ Storyboarding & Scene ============
  {
    id: 'storyboard-9-panel',
    name: '9-Panel Storyboard',
    description: 'Professional 9-panel storyboard grid for commercial ads',
    category: 'Storyboarding & Scene',
    prompt: 'A 9-panel storyboard grid for a [DURATION]-second [PRODUCT/SCENE] ad, [ASPECT] format, dark layout with scene titles and timestamps, each panel showing a different camera angle, professional commercial storyboard style, cinematic composition',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, messy, unprofessional, low quality',
  },
  {
    id: 'storyboard-film-still',
    name: 'Film Still',
    description: 'Cinematic film still with professional color grading and lens effects',
    category: 'Storyboarding & Scene',
    prompt: 'A cinematic film still, [GENRE] genre, [SCENE DESCRIPTION], [LIGHTING] lighting, shot on [LENS TYPE], shallow depth of field, color graded in [GRADE STYLE], professional cinematography, anamorphic lens flare, 35mm film grain',
    style: 'Cinematic',
    aspectRatio: '2.39:1',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '2.39:1',
    negativePrompt: 'amateur, blurry, low quality, unprofessional, flat lighting',
  },

  // ============ Art Styles (Advanced) ============
  {
    id: 'art-watercolor',
    name: 'Watercolor Illustration',
    description: 'Delicate watercolor with soft washes and visible brush texture',
    category: 'Art Styles',
    prompt: 'A delicate watercolor illustration of [SUBJECT], soft color washes, visible brush texture, wet-on-wet technique, [COLOR PALETTE] palette, white paper showing through, fine art quality, traditional watercolor aesthetic',
    style: 'Watercolor',
    aspectRatio: '3:4',
    suggestedStylePreset: 'watercolor',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, sharp edges, heavy, dark, muddy',
  },
  {
    id: 'art-oil-painting',
    name: 'Oil Painting',
    description: 'Rich impasto oil painting with dramatic chiaroscuro lighting',
    category: 'Art Styles',
    prompt: 'An oil painting of [SUBJECT], impasto technique, visible brushstrokes, rich [COLOR] tones, dramatic chiaroscuro lighting, [ERA] style composition, gallery-quality fine art, museum lighting',
    style: 'Oil Painting',
    aspectRatio: '3:4',
    suggestedStylePreset: 'oil-painting',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, flat, smooth, modern, cartoon',
  },
  {
    id: 'art-ink-chinese',
    name: 'Ink & Chinese',
    description: 'Traditional Chinese ink wash painting with calligraphic brushwork',
    category: 'Art Styles',
    prompt: 'A traditional Chinese ink wash painting of [SUBJECT], xuan paper texture, mountains and mist, calligraphic brushwork, [DYNASTY] style landscape, red seal stamp, traditional composition, elegant and serene',
    style: 'Watercolor',
    aspectRatio: '3:4',
    suggestedStylePreset: 'watercolor',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, colorful, western, modern, cartoon',
  },
  {
    id: 'art-pixel',
    name: 'Pixel Art',
    description: 'Detailed pixel art scene with limited color palette and retro gaming vibe',
    category: 'Art Styles',
    prompt: 'A detailed pixel art scene of [SUBJECT], [RESOLUTION] style, limited [NUMBER]-color palette, [GAME ERA] game aesthetic, clean pixel lines, dithering shading, retro gaming vibe',
    style: 'Pixel Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'pixel-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, smooth, high resolution, blurry, anti-aliased',
  },

  // ============ Beauty & Fashion ============
  {
    id: 'beauty-portrait',
    name: 'Beauty Portrait',
    description: 'High-end beauty portrait with flawless retouching and editorial quality',
    category: 'Beauty & Fashion',
    prompt: 'A high-end beauty portrait of [SUBJECT], [LIGHTING] lighting, flawless skin retouching, [MAKEUP STYLE] makeup, [BACKGROUND] background, editorial beauty photography, Vogue quality, 8K skin detail',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, blemishes',
  },
  {
    id: 'beauty-fashion-editorial',
    name: 'Fashion Editorial',
    description: 'High fashion editorial shot with dramatic lighting and designer outfit',
    category: 'Beauty & Fashion',
    prompt: 'A fashion editorial shot of [MODEL] wearing [OUTFIT], [SETTING], [POSE], shot by [PHOTOGRAPHER STYLE], dramatic lighting, [MAGAZINE] editorial style, high fashion, 8K detail',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, casual',
  },

  // ============ Tattoo Design ============
  {
    id: 'tattoo-flash',
    name: 'Tattoo Flash',
    description: 'Professional tattoo flash sheet with bold outlines and stencil-ready design',
    category: 'Tattoo Design',
    prompt: 'A tattoo flash sheet design of [SUBJECT], [STYLE] tattoo style, bold outlines, [COLOR OR B&W], traditional tattoo composition, clean linework, stencil-ready design, professional tattoo artist quality',
    style: 'Illustration',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality',
  },

  // ============ Scientific & Educational ============
  {
    id: 'sci-illustration',
    name: 'Scientific Illustration',
    description: 'Detailed cross-section scientific illustration with labeled features',
    category: 'Scientific & Educational',
    prompt: 'A detailed scientific illustration of [SUBJECT], cross-section view, labeled anatomical features, clean [BACKGROUND] background, [STYLE] illustration style, precision linework, educational quality, vintage naturalist aesthetic',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality, cartoon',
  },
  {
    id: 'sci-research-figure',
    name: 'Research Figure',
    description: 'Clean research paper figure with professional data visualization',
    category: 'Scientific & Educational',
    prompt: 'A clean research paper figure showing [DATA/CONCEPT], professional data visualization, [CHART TYPE] chart, labeled axes, legend, scientific publication quality, Nature/JAMA style, clean layout',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality, decorative',
  },

  // =====================================================
  // BONUS TEMPLATES — to reach 60+ total
  // =====================================================

  // ============ E-commerce & Product Photography (bonus) ============
  {
    id: 'ecommerce-360-spin',
    name: '360° Product Showcase',
    description: 'Multiple-angle product showcase for e-commerce listings',
    category: 'E-commerce & Product Photography',
    prompt: 'A premium [PRODUCT] showcase with multiple angles, front/side/detail views, consistent [COLOR] background, even studio lighting, product details visible, e-commerce listing quality, commercial photography, 8K',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, inconsistent lighting',
  },

  // ============ UI & Social Media Mockup (bonus) ============
  {
    id: 'ui-website-landing',
    name: 'Landing Page Design',
    description: 'Modern SaaS landing page with hero section and features',
    category: 'UI & Social Media Mockup',
    prompt: 'A modern [INDUSTRY] SaaS landing page design, hero section with headline and CTA, feature cards below, [COLOR SCHEME] color scheme, clean typography, glassmorphism elements, responsive layout, Awwwards-quality design',
    style: 'Digital Art',
    aspectRatio: '9:16',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, cluttered, unprofessional, low quality',
  },

  // ============ Character Design (bonus) ============
  {
    id: 'character-mecha-design',
    name: 'Mecha Design Sheet',
    description: 'Detailed mecha/robot design sheet with multiple views and annotations',
    category: 'Character Design',
    prompt: 'A detailed mecha design sheet for [MECHA TYPE], front/side/rear views, mechanical joint details, weapon systems annotated, [COLOR SCHEME] color scheme, technical blueprint annotations, professional mecha concept art, anime-realistic hybrid style',
    style: 'Anime',
    aspectRatio: '16:9',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, blurry, inconsistent, low quality, messy, organic',
  },

  // =====================================================
  // EXPANDED CATEGORIES — 30+ new templates
  // =====================================================

  // ============ Cinematic ============
  {
    id: 'cinematic-car-chase',
    name: 'Car Chase',
    description: 'High-octane cinematic car chase through city streets at night',
    category: 'Cinematic',
    prompt: 'A cinematic car chase scene through rain-soaked city streets at night, motion blur, neon reflections on wet asphalt, dramatic low angle, anamorphic lens flare, Michael Bay style, 35mm film grain',
    style: 'Cinematic',
    aspectRatio: '2.39:1',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '2.39:1',
    negativePrompt: 'static, boring, low quality, blurry, unprofessional',
    icon: '🚗',
  },
  {
    id: 'cinematic-duel',
    name: 'Epic Duel',
    description: 'Two warriors facing off in an epic cinematic duel',
    category: 'Cinematic',
    prompt: 'An epic cinematic duel between two warriors, sparks flying from clashing weapons, dramatic backlight, slow motion feel, shallow depth of field, epic scale, IMAX quality',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'static, boring, low quality, blurry, cartoon',
    icon: '⚔️',
  },
  {
    id: 'cinematic-noir',
    name: 'Film Noir Detective',
    description: 'Classic film noir detective scene with venetian blind shadows',
    category: 'Cinematic',
    prompt: 'A classic film noir scene, detective in trench coat, venetian blind shadows casting stripes across the room, cigarette smoke, dramatic chiaroscuro, black and white with subtle color accent, 1940s atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'colorful, bright, modern, low quality, blurry',
    icon: '🔍',
  },

  // ============ Horror ============
  {
    id: 'horror-abandoned',
    name: 'Abandoned Hospital',
    description: 'Creepy abandoned hospital corridor with flickering lights',
    category: 'Horror',
    prompt: 'A terrifying abandoned hospital corridor, flickering fluorescent lights, peeling paint, medical equipment scattered, shadows lurking, horror movie atmosphere, unsettling, detailed environment, eerie green tint',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'bright, cheerful, clean, cartoon, low quality',
    icon: '🏥',
  },
  {
    id: 'horror-forest',
    name: 'Dark Forest',
    description: 'Eerie dark forest with twisted trees and fog',
    category: 'Horror',
    prompt: 'A dark and eerie forest at midnight, twisted gnarled trees, thick ground fog, pale moonlight filtering through branches, something watching from the shadows, horror atmosphere, unsettling silence, detailed textures',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'bright, cheerful, daytime, cartoon, low quality',
    icon: '🌲',
  },
  {
    id: 'horror-mirror',
    name: 'Haunted Mirror',
    description: 'Old ornate mirror reflecting something that should not be there',
    category: 'Horror',
    prompt: 'An old ornate mirror in a dusty Victorian room, the reflection shows a different scene than reality, something sinister visible in the glass, cracked surface, candlelight flickering, gothic horror atmosphere, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'bright, cheerful, modern, cartoon, low quality',
    icon: '🪞',
  },

  // ============ Romantic ============
  {
    id: 'romantic-sunset',
    name: 'Sunset Embrace',
    description: 'Couple silhouetted against a breathtaking sunset',
    category: 'Romantic',
    prompt: 'A romantic couple embracing in silhouette against a breathtaking sunset, golden hour light, lens flare, soft bokeh, warm color palette, dreamy atmosphere, professional romance photography, cinematic composition',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'cold, harsh, unromantic, low quality, blurry',
    icon: '🌅',
  },
  {
    id: 'romantic-rain',
    name: 'Rainy Day Love',
    description: 'Couple sharing an umbrella in the rain with city lights',
    category: 'Romantic',
    prompt: 'A couple sharing an umbrella on a rainy city street at night, streetlights reflecting on wet pavement, warm glow from shop windows, intimate moment, cinematic romance photography, dreamy bokeh',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'sunny, harsh, cold, low quality, blurry',
    icon: '🌧️',
  },
  {
    id: 'romantic-picnic',
    name: 'Garden Picnic',
    description: 'Romantic picnic in a blooming flower garden',
    category: 'Romantic',
    prompt: 'A romantic picnic setup in a blooming flower garden, checkered blanket, basket with fruit and wine, soft dappled sunlight, butterflies, dreamy pastel colors, idyllic atmosphere, fine art photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dark, gloomy, urban, harsh, low quality',
    icon: '🧺',
  },

  // ============ Vintage ============
  {
    id: 'vintage-polaroid',
    name: 'Polaroid Snapshot',
    description: 'Vintage Polaroid-style photograph with faded colors',
    category: 'Vintage',
    prompt: 'A vintage Polaroid-style photograph, faded warm colors, light leaks, soft focus edges, white border frame, 1970s summer vibes, nostalgic feel, authentic film aesthetic, worn texture',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'modern, sharp, digital, vibrant, clean',
    icon: '📸',
  },
  {
    id: 'vintage-poster',
    name: 'Retro Travel Poster',
    description: 'Vintage travel poster with bold art deco style',
    category: 'Vintage',
    prompt: 'A vintage travel poster in art deco style, bold geometric shapes, rich warm colors, retro typography, 1930s illustration style, golden age of travel, lithograph print quality, elegant composition',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, modern, minimalist, blurry, low quality',
    icon: '🗺️',
  },
  {
    id: 'vintage-sepia',
    name: 'Sepia Portrait',
    description: 'Antique sepia-toned portrait with period clothing',
    category: 'Vintage',
    prompt: 'An antique sepia-toned photographic portrait, period Victorian clothing, formal pose, soft focus edges, original photographic print quality, faded spots, authentic 1800s aesthetic, museum quality',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'color, modern, vibrant, digital, clean',
    icon: '📜',
  },

  // ============ Minimalist ============
  {
    id: 'minimalist-single',
    name: 'Single Object',
    description: 'Clean minimalist single object on solid background',
    category: 'Minimalist',
    prompt: 'A clean minimalist photograph of a single object on a pure solid background, perfect composition, negative space, soft directional lighting, no distractions, elegant simplicity, gallery-quality fine art',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'cluttered, complex, busy, colorful, textured background',
    icon: '⬜',
  },
  {
    id: 'minimalist-line',
    name: 'Continuous Line',
    description: 'Elegant continuous line drawing on white background',
    category: 'Minimalist',
    prompt: 'An elegant continuous line drawing, single flowing line creating a recognizable form, pure white background, black ink, minimal and refined, Picasso-style line art, fine art quality',
    style: 'Line Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'line-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'color, complex, shaded, photorealistic, textured',
    icon: '〰️',
  },
  {
    id: 'minimalist-shadow',
    name: 'Shadow Play',
    description: 'Dramatic shadow patterns from a simple object',
    category: 'Minimalist',
    prompt: 'A dramatic shadow play photograph, simple geometric object casting complex interesting shadows, strong directional light, high contrast black and white, minimalist composition, gallery-quality photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'colorful, complex, busy, low contrast, blurry',
    icon: '🔳',
  },

  // ============ Surreal ============
  {
    id: 'surreal-melting',
    name: 'Melting Reality',
    description: 'Dalí-inspired melting objects in a dreamlike landscape',
    category: 'Surreal',
    prompt: 'A surreal Dalí-inspired scene with melting objects, dreamlike landscape, impossible architecture, distorted perspective, vivid colors, bizarre yet beautiful, Salvador Dalí style, fine art surrealism, museum quality',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, boring, photorealistic, mundane',
    icon: '🕰️',
  },
  {
    id: 'surreal-floating',
    name: 'Floating Islands',
    description: 'Impossible floating islands connected by waterfalls',
    category: 'Surreal',
    prompt: 'Impossible floating islands in a surreal sky, connected by impossible waterfalls flowing upward, lush vegetation, tiny buildings, atmospheric perspective, Studio Ghibli meets Dalí, dreamlike quality, magical realism',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, mundane, low quality, blurry',
    icon: '🏝️',
  },
  {
    id: 'surreal-doors',
    name: 'Infinite Doors',
    description: 'Endless hallway of doors each leading to a different world',
    category: 'Surreal',
    prompt: 'An endless hallway of doors, each door slightly different, each open door reveals a completely different world — desert, ocean, forest, space, city, fire — impossible architecture, Escher-like perspective, surrealism, highly detailed',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, single scene, mundane, low quality',
    icon: '🚪',
  },

  // ============ Portrait (expanded) ============
  {
    id: 'portrait-cyberpunk',
    name: 'Cyberpunk Portrait',
    description: 'Neon-lit cyberpunk character portrait with tech implants',
    category: 'Portrait',
    prompt: 'A cyberpunk portrait, neon-lit face, glowing tech implants, rain-slicked skin, holographic reflections, vibrant cyan and magenta, futuristic urban background, high detail, Blade Runner style',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'bright, cheerful, natural, low quality, blurry',
    icon: '🤖',
  },
  {
    id: 'portrait-double',
    name: 'Double Exposure',
    description: 'Artistic double exposure portrait blending with nature',
    category: 'Portrait',
    prompt: 'An artistic double exposure portrait, silhouetted profile filled with a forest landscape, blended layers, nature and humanity as one, fine art photography, soft ethereal quality, high contrast',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'flat, simple, cartoon, low quality, blurry',
    icon: '🌿',
  },

  // ============ Landscape (expanded) ============
  {
    id: 'landscape-underwater',
    name: 'Underwater Kingdom',
    description: 'Vibrant coral reef with exotic fish in crystal-clear water',
    category: 'Landscape',
    prompt: 'A vibrant underwater coral reef kingdom, crystal-clear turquoise water, exotic tropical fish, sunbeams filtering through the surface, colorful coral formations, National Geographic quality, underwater photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dark, murky, low quality, blurry, cartoon',
    icon: '🐠',
  },
  {
    id: 'landscape-desert',
    name: 'Desert Dunes',
    description: 'Sweeping sand dunes at sunset with dramatic shadows',
    category: 'Landscape',
    prompt: 'Sweeping sand dunes at sunset, dramatic long shadows, golden and amber tones, wind-sculpted ridges, vast empty desert, Lawrence of Arabia scale, National Geographic quality, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'green, lush, cold, low quality, blurry',
    icon: '🏜️',
  },

  // ============ Fantasy (expanded) ============
  {
    id: 'fantasy-dragon',
    name: 'Dragon\'s Lair',
    description: 'Majestic dragon perched atop a mountain of treasure',
    category: 'Fantasy',
    prompt: 'A majestic dragon perched atop a mountain of gold treasure, deep within a volcanic cave, glowing embers, bioluminescent crystals, scales shimmering, treasure coins scattered, epic fantasy art, highly detailed',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'modern, realistic, boring, low quality, blurry',
    icon: '🐉',
  },
  {
    id: 'fantasy-underwater-city',
    name: 'Atlantis',
    description: 'Magnificent underwater city with bioluminescent architecture',
    category: 'Fantasy',
    prompt: 'The magnificent lost city of Atlantis, underwater, bioluminescent architecture, coral-encrusted towers, shafts of sunlight from above, schools of exotic fish, ancient Greek-inspired structures, fantasy concept art, epic scale',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dry, modern, realistic, low quality, blurry',
    icon: '🏛️',
  },

  // ============ Sci-Fi (expanded) ============
  {
    id: 'scifi-terraform',
    name: 'Terraforming',
    description: 'Massive terraforming machine transforming a barren planet',
    category: 'Sci-Fi',
    prompt: 'A massive terraforming machine on a barren alien planet, pumping atmosphere into the sky, green zones spreading from the machine, dramatic scale, industrial sci-fi, concept art, highly detailed, 8K',
    style: '3D Render',
    aspectRatio: '16:9',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'fantasy, medieval, organic, low quality, blurry',
    icon: '🌍',
  },
  {
    id: 'scifi-hologram',
    name: 'Holographic Interface',
    description: 'Person interacting with a holographic data interface',
    category: 'Sci-Fi',
    prompt: 'A person interacting with a holographic data interface, floating transparent screens, gesture-based controls, blue and cyan light, dark room, Minority Report style, sci-fi concept, photorealistic',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'fantasy, medieval, low tech, low quality, blurry',
    icon: '💻',
  },

  // ============ Architecture (expanded) ============
  {
    id: 'architecture-brutalist',
    name: 'Brutalist Monument',
    description: 'Imposing brutalist concrete structure with dramatic sky',
    category: 'Architecture',
    prompt: 'An imposing brutalist concrete structure, raw concrete textures, geometric massing, dramatic overcast sky, documentary architecture photography, monumental scale, strict symmetry, fine art photography quality',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'colorful, ornate, traditional, warm, low quality',
    icon: '🏗️',
  },

  // ============ Food (expanded) ============
  {
    id: 'food-sushi',
    name: 'Sushi Artistry',
    description: 'Exquisite sushi platter with artistic arrangement',
    category: 'Food',
    prompt: 'An exquisite sushi platter, artistic arrangement on black slate, wasabi and ginger garnish, chopsticks, sake glass, dramatic overhead lighting, Japanese restaurant atmosphere, food photography masterpiece, ultra detailed',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'unappetizing, messy, low quality, blurry, western food',
    icon: '🍣',
  },
  {
    id: 'food-coffee',
    name: 'Coffee Art',
    description: 'Perfect latte art with warm café atmosphere',
    category: 'Food',
    prompt: 'A perfect latte art rosetta in a ceramic cup, warm café atmosphere, wooden table, scattered coffee beans, soft morning light, steam rising, cozy ambient, professional coffee photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'cold, harsh, messy, low quality, blurry',
    icon: '☕',
  },

  // ============ Fashion (expanded) ============
  {
    id: 'fashion-avantgarde',
    name: 'Avant-Garde',
    description: 'Avant-garde fashion with geometric sculptural clothing',
    category: 'Fashion',
    prompt: 'An avant-garde fashion photograph, model wearing geometric sculptural clothing, abstract silhouettes, unconventional materials, dramatic studio lighting, editorial fashion, Alexander McQueen inspired, haute couture',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'casual, simple, boring, low quality, blurry',
    icon: '🎭',
  },

  // ============ Product (expanded) ============
  {
    id: 'product-floating',
    name: 'Floating Product',
    description: 'Product magically floating with dynamic splash effects',
    category: 'Product',
    prompt: 'A product magically floating in mid-air, dynamic splash of water or particles around it, studio lighting, freeze-frame effect, commercial product photography, dramatic composition, 8K detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'boring, static, low quality, blurry, messy',
    icon: '✨',
  },

  // ============ Abstract (expanded) ============
  {
    id: 'abstract-fractal',
    name: 'Fractal Universe',
    description: 'Mesmerizing fractal pattern with infinite depth',
    category: 'Abstract',
    prompt: 'A mesmerizing fractal pattern, infinite depth, self-similar structures at every scale, vibrant electric colors, mathematical beauty, digital art, psychedelic, high resolution render',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'realistic, photographic, simple, boring, low quality',
    icon: '🔮',
  },

  // ============ Animals (expanded) ============
  {
    id: 'animals-underwater',
    name: 'Ocean Giant',
    description: 'Massive whale gliding through sunlit ocean depths',
    category: 'Animals',
    prompt: 'A massive whale gliding gracefully through sunlit ocean depths, rays of light from above, tiny divers for scale, deep blue water, marine life, underwater photography, National Geographic quality, awe-inspiring',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'land, dry, cartoon, low quality, blurry',
    icon: '🐋',
  },
];

// Category icons (emoji) for display
const CATEGORY_ICONS: Record<string, string> = {
  Portrait: '👤',
  Landscape: '🏔️',
  Product: '📦',
  Abstract: '🎨',
  Fantasy: '🧙',
  'Sci-Fi': '🚀',
  Architecture: '🏛️',
  Food: '🍽️',
  Fashion: '👗',
  Animals: '🦁',
  Cinematic: '🎬',
  Horror: '👻',
  Romantic: '💕',
  Vintage: '📻',
  Minimalist: '⬜',
  Surreal: '🕰️',
  'E-commerce & Product Photography': '🛍️',
  'UI & Social Media Mockup': '📱',
  'Ad Creative & Campaigns': '📣',
  'Infographics & Data Visualization': '📊',
  'Character Design': '🧍',
  'Architecture & Interior': '🏠',
  'Storyboarding & Scene': '🎬',
  'Art Styles': '🎨',
  'Beauty & Fashion': '💄',
  'Tattoo Design': '🖋️',
  'Scientific & Educational': '🧪',
};

const CATEGORY_ORDER = [
  'Portrait',
  'Landscape',
  'Product',
  'Abstract',
  'Fantasy',
  'Sci-Fi',
  'Architecture',
  'Food',
  'Fashion',
  'Animals',
  'Cinematic',
  'Horror',
  'Romantic',
  'Vintage',
  'Minimalist',
  'Surreal',
  'E-commerce & Product Photography',
  'UI & Social Media Mockup',
  'Ad Creative & Campaigns',
  'Infographics & Data Visualization',
  'Character Design',
  'Architecture & Interior',
  'Storyboarding & Scene',
  'Art Styles',
  'Beauty & Fashion',
  'Tattoo Design',
  'Scientific & Educational',
];

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const category = searchParams.get('category');
    const search = searchParams.get('search');

    let templates = PROMPT_TEMPLATES;

    // Filter by category
    if (category && category !== 'all') {
      templates = templates.filter((t) => t.category === category);
    }

    // Filter by search
    if (search) {
      const q = search.toLowerCase();
      templates = templates.filter(
        (t) =>
          t.name.toLowerCase().includes(q) ||
          t.category.toLowerCase().includes(q) ||
          t.prompt.toLowerCase().includes(q) ||
          (t.description && t.description.toLowerCase().includes(q))
      );
    }

    // Build categories with counts
    const categories = CATEGORY_ORDER.map((cat) => ({
      name: cat,
      icon: CATEGORY_ICONS[cat] || '📁',
      count: PROMPT_TEMPLATES.filter((t) => t.category === cat).length,
    }));

    return NextResponse.json({
      templates,
      categories,
      total: PROMPT_TEMPLATES.length,
    });
  } catch (error) {
    console.error('Prompt templates error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch templates' },
      { status: 500 }
    );
  }
}
