// Curated prompt templates library — Part 2 (Cinema & Expanded templates)
export const PROMPT_TEMPLATES_PART_2 = [
  {
    id: 'art-oil-painting',
    name: 'Oil Painting',
    description: 'Rich impasto oil painting with dramatic chiaroscuro lighting',
    category: 'Art Styles',
    prompt: 'An oil painting of [SUBJECT], impasto technique, visible brushstrokes, rich [COLOR] tones, dramatic chiaroscuro lighting, [ERA] style composition, gallery-quality fine art, museum lighting',
    style: 'Oil Painting',
    aspectRatio: '3:4',
    suggestedStylePreset: 'oil-painting',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, flat, smooth, modern, cartoon',
  },
  {
    id: 'art-ink-chinese',
    name: 'Ink & Chinese',
    description: 'Traditional Chinese ink wash painting with calligraphic brushwork',
    category: 'Art Styles',
    prompt: 'A traditional Chinese ink wash painting of [SUBJECT], xuan paper texture, mountains and mist, calligraphic brushwork, [DYNASTY] style landscape, red seal stamp, traditional composition, elegant and serene',
    style: 'Watercolor',
    aspectRatio: '3:4',
    suggestedStylePreset: 'watercolor',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, colorful, western, modern, cartoon',
  },
  {
    id: 'art-pixel',
    name: 'Pixel Art',
    description: 'Detailed pixel art scene with limited color palette and retro gaming vibe',
    category: 'Art Styles',
    prompt: 'A detailed pixel art scene of [SUBJECT], [RESOLUTION] style, limited [NUMBER]-color palette, [GAME ERA] game aesthetic, clean pixel lines, dithering shading, retro gaming vibe',
    style: 'Pixel Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'pixel-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, smooth, high resolution, blurry, anti-aliased',
  },

  // ============ Beauty & Fashion ============
  {
    id: 'beauty-portrait',
    name: 'Beauty Portrait',
    description: 'High-end beauty portrait with flawless retouching and editorial quality',
    category: 'Beauty & Fashion',
    prompt: 'A high-end beauty portrait of [SUBJECT], [LIGHTING] lighting, flawless skin retouching, [MAKEUP STYLE] makeup, [BACKGROUND] background, editorial beauty photography, Vogue quality, 8K skin detail',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, blemishes',
  },
  {
    id: 'beauty-fashion-editorial',
    name: 'Fashion Editorial',
    description: 'High fashion editorial shot with dramatic lighting and designer outfit',
    category: 'Beauty & Fashion',
    prompt: 'A fashion editorial shot of [MODEL] wearing [OUTFIT], [SETTING], [POSE], shot by [PHOTOGRAPHER STYLE], dramatic lighting, [MAGAZINE] editorial style, high fashion, 8K detail',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, casual',
  },

  // ============ Tattoo Design ============
  {
    id: 'tattoo-flash',
    name: 'Tattoo Flash',
    description: 'Professional tattoo flash sheet with bold outlines and stencil-ready design',
    category: 'Tattoo Design',
    prompt: 'A tattoo flash sheet design of [SUBJECT], [STYLE] tattoo style, bold outlines, [COLOR OR B&W], traditional tattoo composition, clean linework, stencil-ready design, professional tattoo artist quality',
    style: 'Illustration',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality',
  },

  // ============ Scientific & Educational ============
  {
    id: 'sci-illustration',
    name: 'Scientific Illustration',
    description: 'Detailed cross-section scientific illustration with labeled features',
    category: 'Scientific & Educational',
    prompt: 'A detailed scientific illustration of [SUBJECT], cross-section view, labeled anatomical features, clean [BACKGROUND] background, [STYLE] illustration style, precision linework, educational quality, vintage naturalist aesthetic',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality, cartoon',
  },
  {
    id: 'sci-research-figure',
    name: 'Research Figure',
    description: 'Clean research paper figure with professional data visualization',
    category: 'Scientific & Educational',
    prompt: 'A clean research paper figure showing [DATA/CONCEPT], professional data visualization, [CHART TYPE] chart, labeled axes, legend, scientific publication quality, Nature/JAMA style, clean layout',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, blurry, messy, unprofessional, low quality, decorative',
  },

  // =====================================================
  // BONUS TEMPLATES — to reach 60+ total
  // =====================================================

  // ============ E-commerce & Product Photography (bonus) ============
  {
    id: 'ecommerce-360-spin',
    name: '360° Product Showcase',
    description: 'Multiple-angle product showcase for e-commerce listings',
    category: 'E-commerce & Product Photography',
    prompt: 'A premium [PRODUCT] showcase with multiple angles, front/side/detail views, consistent [COLOR] background, even studio lighting, product details visible, e-commerce listing quality, commercial photography, 8K',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, inconsistent lighting',
  },

  // ============ UI & Social Media Mockup (bonus) ============
  {
    id: 'ui-website-landing',
    name: 'Landing Page Design',
    description: 'Modern SaaS landing page with hero section and features',
    category: 'UI & Social Media Mockup',
    prompt: 'A modern [INDUSTRY] SaaS landing page design, hero section with headline and CTA, feature cards below, [COLOR SCHEME] color scheme, clean typography, glassmorphism elements, responsive layout, Awwwards-quality design',
    style: 'Digital Art',
    aspectRatio: '9:16',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, cluttered, unprofessional, low quality',
  },

  // ============ Character Design (bonus) ============
  {
    id: 'character-mecha-design',
    name: 'Mecha Design Sheet',
    description: 'Detailed mecha/robot design sheet with multiple views and annotations',
    category: 'Character Design',
    prompt: 'A detailed mecha design sheet for [MECHA TYPE], front/side/rear views, mechanical joint details, weapon systems annotated, [COLOR SCHEME] color scheme, technical blueprint annotations, professional mecha concept art, anime-realistic hybrid style',
    style: 'Anime',
    aspectRatio: '16:9',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'photorealistic, blurry, inconsistent, low quality, messy, organic',
  },

  // =====================================================
  // EXPANDED CATEGORIES — 30+ new templates
  // =====================================================

  // ============ Cinematic ============
  {
    id: 'cinematic-car-chase',
    name: 'Car Chase',
    description: 'High-octane cinematic car chase through city streets at night',
    category: 'Cinematic',
    prompt: 'A cinematic car chase scene through rain-soaked city streets at night, motion blur, neon reflections on wet asphalt, dramatic low angle, anamorphic lens flare, Michael Bay style, 35mm film grain',
    style: 'Cinematic',
    aspectRatio: '2.39:1',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '2.39:1',
    negativePrompt: 'static, boring, low quality, blurry, unprofessional',
    icon: '🚗',
  },
  {
    id: 'cinematic-duel',
    name: 'Epic Duel',
    description: 'Two warriors facing off in an epic cinematic duel',
    category: 'Cinematic',
    prompt: 'An epic cinematic duel between two warriors, sparks flying from clashing weapons, dramatic backlight, slow motion feel, shallow depth of field, epic scale, IMAX quality',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'static, boring, low quality, blurry, cartoon',
    icon: '⚔️',
  },
  {
    id: 'cinematic-noir',
    name: 'Film Noir Detective',
    description: 'Classic film noir detective scene with venetian blind shadows',
    category: 'Cinematic',
    prompt: 'A classic film noir scene, detective in trench coat, venetian blind shadows casting stripes across the room, cigarette smoke, dramatic chiaroscuro, black and white with subtle color accent, 1940s atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'colorful, bright, modern, low quality, blurry',
    icon: '🔍',
  },

  // ============ Horror ============
  {
    id: 'horror-abandoned',
    name: 'Abandoned Hospital',
    description: 'Creepy abandoned hospital corridor with flickering lights',
    category: 'Horror',
    prompt: 'A terrifying abandoned hospital corridor, flickering fluorescent lights, peeling paint, medical equipment scattered, shadows lurking, horror movie atmosphere, unsettling, detailed environment, eerie green tint',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'bright, cheerful, clean, cartoon, low quality',
    icon: '🏥',
  },
  {
    id: 'horror-forest',
    name: 'Dark Forest',
    description: 'Eerie dark forest with twisted trees and fog',
    category: 'Horror',
    prompt: 'A dark and eerie forest at midnight, twisted gnarled trees, thick ground fog, pale moonlight filtering through branches, something watching from the shadows, horror atmosphere, unsettling silence, detailed textures',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'bright, cheerful, daytime, cartoon, low quality',
    icon: '🌲',
  },
  {
    id: 'horror-mirror',
    name: 'Haunted Mirror',
    description: 'Old ornate mirror reflecting something that should not be there',
    category: 'Horror',
    prompt: 'An old ornate mirror in a dusty Victorian room, the reflection shows a different scene than reality, something sinister visible in the glass, cracked surface, candlelight flickering, gothic horror atmosphere, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'bright, cheerful, modern, cartoon, low quality',
    icon: '🪞',
  },

  // ============ Romantic ============
  {
    id: 'romantic-sunset',
    name: 'Sunset Embrace',
    description: 'Couple silhouetted against a breathtaking sunset',
    category: 'Romantic',
    prompt: 'A romantic couple embracing in silhouette against a breathtaking sunset, golden hour light, lens flare, soft bokeh, warm color palette, dreamy atmosphere, professional romance photography, cinematic composition',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'cold, harsh, unromantic, low quality, blurry',
    icon: '🌅',
  },
  {
    id: 'romantic-rain',
    name: 'Rainy Day Love',
    description: 'Couple sharing an umbrella in the rain with city lights',
    category: 'Romantic',
    prompt: 'A couple sharing an umbrella on a rainy city street at night, streetlights reflecting on wet pavement, warm glow from shop windows, intimate moment, cinematic romance photography, dreamy bokeh',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'sunny, harsh, cold, low quality, blurry',
    icon: '🌧️',
  },
  {
    id: 'romantic-picnic',
    name: 'Garden Picnic',
    description: 'Romantic picnic in a blooming flower garden',
    category: 'Romantic',
    prompt: 'A romantic picnic setup in a blooming flower garden, checkered blanket, basket with fruit and wine, soft dappled sunlight, butterflies, dreamy pastel colors, idyllic atmosphere, fine art photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dark, gloomy, urban, harsh, low quality',
    icon: '🧺',
  },

  // ============ Vintage ============
  {
    id: 'vintage-polaroid',
    name: 'Polaroid Snapshot',
    description: 'Vintage Polaroid-style photograph with faded colors',
    category: 'Vintage',
    prompt: 'A vintage Polaroid-style photograph, faded warm colors, light leaks, soft focus edges, white border frame, 1970s summer vibes, nostalgic feel, authentic film aesthetic, worn texture',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'modern, sharp, digital, vibrant, clean',
    icon: '📸',
  },
  {
    id: 'vintage-poster',
    name: 'Retro Travel Poster',
    description: 'Vintage travel poster with bold art deco style',
    category: 'Vintage',
    prompt: 'A vintage travel poster in art deco style, bold geometric shapes, rich warm colors, retro typography, 1930s illustration style, golden age of travel, lithograph print quality, elegant composition',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, modern, minimalist, blurry, low quality',
    icon: '🗺️',
  },
  {
    id: 'vintage-sepia',
    name: 'Sepia Portrait',
    description: 'Antique sepia-toned portrait with period clothing',
    category: 'Vintage',
    prompt: 'An antique sepia-toned photographic portrait, period Victorian clothing, formal pose, soft focus edges, original photographic print quality, faded spots, authentic 1800s aesthetic, museum quality',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'color, modern, vibrant, digital, clean',
    icon: '📜',
  },

  // ============ Minimalist ============
  {
    id: 'minimalist-single',
    name: 'Single Object',
    description: 'Clean minimalist single object on solid background',
    category: 'Minimalist',
    prompt: 'A clean minimalist photograph of a single object on a pure solid background, perfect composition, negative space, soft directional lighting, no distractions, elegant simplicity, gallery-quality fine art',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'cluttered, complex, busy, colorful, textured background',
    icon: '⬜',
  },
  {
    id: 'minimalist-line',
    name: 'Continuous Line',
    description: 'Elegant continuous line drawing on white background',
    category: 'Minimalist',
    prompt: 'An elegant continuous line drawing, single flowing line creating a recognizable form, pure white background, black ink, minimal and refined, Picasso-style line art, fine art quality',
    style: 'Line Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'line-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'color, complex, shaded, photorealistic, textured',
    icon: '〰️',
  },
  {
    id: 'minimalist-shadow',
    name: 'Shadow Play',
    description: 'Dramatic shadow patterns from a simple object',
    category: 'Minimalist',
    prompt: 'A dramatic shadow play photograph, simple geometric object casting complex interesting shadows, strong directional light, high contrast black and white, minimalist composition, gallery-quality photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'colorful, complex, busy, low contrast, blurry',
    icon: '🔳',
  },

  // ============ Surreal ============
  {
    id: 'surreal-melting',
    name: 'Melting Reality',
    description: 'Dalí-inspired melting objects in a dreamlike landscape',
    category: 'Surreal',
    prompt: 'A surreal Dalí-inspired scene with melting objects, dreamlike landscape, impossible architecture, distorted perspective, vivid colors, bizarre yet beautiful, Salvador Dalí style, fine art surrealism, museum quality',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, boring, photorealistic, mundane',
    icon: '🕰️',
  },
  {
    id: 'surreal-floating',
    name: 'Floating Islands',
    description: 'Impossible floating islands connected by waterfalls',
    category: 'Surreal',
    prompt: 'Impossible floating islands in a surreal sky, connected by impossible waterfalls flowing upward, lush vegetation, tiny buildings, atmospheric perspective, Studio Ghibli meets Dalí, dreamlike quality, magical realism',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, mundane, low quality, blurry',
    icon: '🏝️',
  },
  {
    id: 'surreal-doors',
    name: 'Infinite Doors',
    description: 'Endless hallway of doors each leading to a different world',
    category: 'Surreal',
    prompt: 'An endless hallway of doors, each door slightly different, each open door reveals a completely different world — desert, ocean, forest, space, city, fire — impossible architecture, Escher-like perspective, surrealism, highly detailed',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic, normal, single scene, mundane, low quality',
    icon: '🚪',
  },

  // ============ Portrait (expanded) ============
  {
    id: 'portrait-cyberpunk',
    name: 'Cyberpunk Portrait',
    description: 'Neon-lit cyberpunk character portrait with tech implants',
    category: 'Portrait',
    prompt: 'A cyberpunk portrait, neon-lit face, glowing tech implants, rain-slicked skin, holographic reflections, vibrant cyan and magenta, futuristic urban background, high detail, Blade Runner style',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'bright, cheerful, natural, low quality, blurry',
    icon: '🤖',
  },
  {
    id: 'portrait-double',
    name: 'Double Exposure',
    description: 'Artistic double exposure portrait blending with nature',
    category: 'Portrait',
    prompt: 'An artistic double exposure portrait, silhouetted profile filled with a forest landscape, blended layers, nature and humanity as one, fine art photography, soft ethereal quality, high contrast',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'flat, simple, cartoon, low quality, blurry',
    icon: '🌿',
  },

  // ============ Landscape (expanded) ============
  {
    id: 'landscape-underwater',
    name: 'Underwater Kingdom',
    description: 'Vibrant coral reef with exotic fish in crystal-clear water',
    category: 'Landscape',
    prompt: 'A vibrant underwater coral reef kingdom, crystal-clear turquoise water, exotic tropical fish, sunbeams filtering through the surface, colorful coral formations, National Geographic quality, underwater photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dark, murky, low quality, blurry, cartoon',
    icon: '🐠',
  },
  {
    id: 'landscape-desert',
    name: 'Desert Dunes',
    description: 'Sweeping sand dunes at sunset with dramatic shadows',
    category: 'Landscape',
    prompt: 'Sweeping sand dunes at sunset, dramatic long shadows, golden and amber tones, wind-sculpted ridges, vast empty desert, Lawrence of Arabia scale, National Geographic quality, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'green, lush, cold, low quality, blurry',
    icon: '🏜️',
  },

  // ============ Fantasy (expanded) ============
  {
    id: 'fantasy-dragon',
    name: 'Dragon\'s Lair',
    description: 'Majestic dragon perched atop a mountain of treasure',
    category: 'Fantasy',
    prompt: 'A majestic dragon perched atop a mountain of gold treasure, deep within a volcanic cave, glowing embers, bioluminescent crystals, scales shimmering, treasure coins scattered, epic fantasy art, highly detailed',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'modern, realistic, boring, low quality, blurry',
    icon: '🐉',
  },
  {
    id: 'fantasy-underwater-city',
    name: 'Atlantis',
    description: 'Magnificent underwater city with bioluminescent architecture',
    category: 'Fantasy',
    prompt: 'The magnificent lost city of Atlantis, underwater, bioluminescent architecture, coral-encrusted towers, shafts of sunlight from above, schools of exotic fish, ancient Greek-inspired structures, fantasy concept art, epic scale',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'dry, modern, realistic, low quality, blurry',
    icon: '🏛️',
  },

  // ============ Sci-Fi (expanded) ============
  {
    id: 'scifi-terraform',
    name: 'Terraforming',
    description: 'Massive terraforming machine transforming a barren planet',
    category: 'Sci-Fi',
    prompt: 'A massive terraforming machine on a barren alien planet, pumping atmosphere into the sky, green zones spreading from the machine, dramatic scale, industrial sci-fi, concept art, highly detailed, 8K',
    style: '3D Render',
    aspectRatio: '16:9',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'fantasy, medieval, organic, low quality, blurry',
    icon: '🌍',
  },
  {
    id: 'scifi-hologram',
    name: 'Holographic Interface',
    description: 'Person interacting with a holographic data interface',
    category: 'Sci-Fi',
    prompt: 'A person interacting with a holographic data interface, floating transparent screens, gesture-based controls, blue and cyan light, dark room, Minority Report style, sci-fi concept, photorealistic',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'fantasy, medieval, low tech, low quality, blurry',
    icon: '💻',
  },

  // ============ Architecture (expanded) ============
  {
    id: 'architecture-brutalist',
    name: 'Brutalist Monument',
    description: 'Imposing brutalist concrete structure with dramatic sky',
    category: 'Architecture',
    prompt: 'An imposing brutalist concrete structure, raw concrete textures, geometric massing, dramatic overcast sky, documentary architecture photography, monumental scale, strict symmetry, fine art photography quality',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'colorful, ornate, traditional, warm, low quality',
    icon: '🏗️',
  },

  // ============ Food (expanded) ============
  {
    id: 'food-sushi',
    name: 'Sushi Artistry',
    description: 'Exquisite sushi platter with artistic arrangement',
    category: 'Food',
    prompt: 'An exquisite sushi platter, artistic arrangement on black slate, wasabi and ginger garnish, chopsticks, sake glass, dramatic overhead lighting, Japanese restaurant atmosphere, food photography masterpiece, ultra detailed',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'unappetizing, messy, low quality, blurry, western food',
    icon: '🍣',
  },
  {
    id: 'food-coffee',
    name: 'Coffee Art',
    description: 'Perfect latte art with warm café atmosphere',
    category: 'Food',
    prompt: 'A perfect latte art rosetta in a ceramic cup, warm café atmosphere, wooden table, scattered coffee beans, soft morning light, steam rising, cozy ambient, professional coffee photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'cold, harsh, messy, low quality, blurry',
    icon: '☕',
  },

  // ============ Fashion (expanded) ============
  {
    id: 'fashion-avantgarde',
    name: 'Avant-Garde',
    description: 'Avant-garde fashion with geometric sculptural clothing',
    category: 'Fashion',
    prompt: 'An avant-garde fashion photograph, model wearing geometric sculptural clothing, abstract silhouettes, unconventional materials, dramatic studio lighting, editorial fashion, Alexander McQueen inspired, haute couture',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'casual, simple, boring, low quality, blurry',
    icon: '🎭',
  },

  // ============ Product (expanded) ============
  {
    id: 'product-floating',
    name: 'Floating Product',
    description: 'Product magically floating with dynamic splash effects',
    category: 'Product',
    prompt: 'A product magically floating in mid-air, dynamic splash of water or particles around it, studio lighting, freeze-frame effect, commercial product photography, dramatic composition, 8K detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'boring, static, low quality, blurry, messy',
    icon: '✨',
  },

  // ============ Abstract (expanded) ============
  {
    id: 'abstract-fractal',
    name: 'Fractal Universe',
    description: 'Mesmerizing fractal pattern with infinite depth',
    category: 'Abstract',
    prompt: 'A mesmerizing fractal pattern, infinite depth, self-similar structures at every scale, vibrant electric colors, mathematical beauty, digital art, psychedelic, high resolution render',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'realistic, photographic, simple, boring, low quality',
    icon: '🔮',
  },

  // ============ Animals (expanded) ============
  {
    id: 'animals-underwater',
    name: 'Ocean Giant',
    description: 'Massive whale gliding through sunlit ocean depths',
    category: 'Animals',
    prompt: 'A massive whale gliding gracefully through sunlit ocean depths, rays of light from above, tiny divers for scale, deep blue water, marine life, underwater photography, National Geographic quality, awe-inspiring',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'land, dry, cartoon, low quality, blurry',
    icon: '🐋',
  },
];
