// Curated prompt templates library — Part 1 (Image & Professional templates)
export const PROMPT_TEMPLATES_PART_1 = [
  // ============ Portrait ============
  {
    id: 'portrait-professional',
    name: 'Professional Headshot',
    description: 'Clean, corporate-style headshot with studio lighting',
    category: 'Portrait',
    prompt: 'A professional headshot portrait of a person, studio lighting, shallow depth of field, 85mm lens, clean background, high detail, corporate style',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'portrait-creative',
    name: 'Creative Portrait',
    description: 'Dramatic fashion portrait with colorful rim light',
    category: 'Portrait',
    prompt: 'A creative portrait with dramatic lighting, colorful rim light, artistic composition, blurred bokeh background, expressive pose, high-end fashion photography',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'portrait-vintage',
    name: 'Vintage Portrait',
    description: 'Retro Hollywood glamour with film grain',
    category: 'Portrait',
    prompt: 'A vintage-style portrait, soft warm lighting, film grain, retro color palette, classic pose, 1940s Hollywood glamour, timeless elegance',
    style: 'Oil Painting',
    aspectRatio: '3:4',
    suggestedStylePreset: 'oil-painting',
    suggestedAspectRatio: '3:4',
  },

  // ============ Landscape ============
  {
    id: 'landscape-mountains',
    name: 'Mountain Vista',
    description: 'Breathtaking alpine mountain landscape at golden hour',
    category: 'Landscape',
    prompt: 'A breathtaking mountain landscape at golden hour, dramatic clouds, snow-capped peaks, reflection in alpine lake, ultra detailed, 8k resolution, National Geographic quality',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'landscape-ocean',
    name: 'Ocean Sunset',
    description: 'Dramatic ocean sunset with crashing waves',
    category: 'Landscape',
    prompt: 'A stunning ocean sunset scene, crashing waves on rocky shore, vibrant orange and purple sky, long exposure water effect, dramatic seascape photography',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'landscape-aurora',
    name: 'Northern Lights',
    description: 'Spectacular aurora borealis over a frozen lake',
    category: 'Landscape',
    prompt: 'A spectacular aurora borealis display over a frozen lake, vibrant green and purple lights dancing in the night sky, snow-covered pine trees, long exposure photography',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },

  // ============ Product ============
  {
    id: 'product-clean',
    name: 'Clean Product Shot',
    description: 'Professional e-commerce product on white background',
    category: 'Product',
    prompt: 'A professional product photography shot on clean white background, soft studio lighting, commercial quality, sharp focus, no shadows, e-commerce style',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'product-lifestyle',
    name: 'Lifestyle Product',
    description: 'Product in natural setting with warm ambient lighting',
    category: 'Product',
    prompt: 'A lifestyle product photography shot, product in natural setting, warm ambient lighting, shallow depth of field, premium feel, brand storytelling composition',
    style: 'Photorealistic',
    aspectRatio: '4:3',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:3',
  },
  {
    id: 'product-minimal',
    name: 'Minimalist Product',
    description: 'Apple-style product shot on gradient background',
    category: 'Product',
    prompt: 'A minimalist product shot on gradient background, soft directional lighting, clean lines, modern aesthetic, subtle reflections, Apple-style product photography',
    style: '3D Render',
    aspectRatio: '1:1',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '1:1',
  },

  // ============ Abstract ============
  {
    id: 'abstract-fluid',
    name: 'Fluid Dynamics',
    description: 'Swirling colorful fluid dynamics composition',
    category: 'Abstract',
    prompt: 'An abstract fluid dynamics composition, swirling vibrant colors, organic shapes, metallic sheen, marble texture, high contrast, mesmerizing patterns',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'abstract-geometric',
    name: 'Geometric Patterns',
    description: 'Sacred geometry with bold colors and symmetry',
    category: 'Abstract',
    prompt: 'Abstract geometric patterns, sacred geometry, interlocking shapes, bold color palette, mathematical precision, modern art, clean lines and symmetry',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'abstract-ink',
    name: 'Ink in Water',
    description: 'Colorful ink drops dispersing in clear water',
    category: 'Abstract',
    prompt: 'Abstract ink in water photography, colorful ink drops dispersing in clear water, organic flowing shapes, high-speed capture, vibrant color diffusion, macro detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },

  // ============ Fantasy ============
  {
    id: 'fantasy-castle',
    name: 'Enchanted Castle',
    description: 'Epic floating castle with bioluminescent plants',
    category: 'Fantasy',
    prompt: 'An epic enchanted castle on a floating island, magical atmosphere, ethereal lighting, bioluminescent plants, mystical fog, fantasy art, detailed environment',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'fantasy-creature',
    name: 'Mythical Creature',
    description: 'Majestic mythical creature with magical aura',
    category: 'Fantasy',
    prompt: 'A majestic mythical creature in its natural habitat, fantasy illustration, magical aura, dramatic lighting, detailed scales and feathers, epic composition',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fantasy-forest',
    name: 'Mystical Forest',
    description: 'Glowing mushrooms and fairy lights in an enchanted forest',
    category: 'Fantasy',
    prompt: 'A mystical ancient forest with glowing mushrooms and fairy lights, magical atmosphere, volumetric light rays, enchanted pathway, fantasy landscape',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },

  // ============ Sci-Fi ============
  {
    id: 'scifi-city',
    name: 'Cyberpunk City',
    description: 'Neon-lit cyberpunk megacity at night',
    category: 'Sci-Fi',
    prompt: 'A cyberpunk megacity at night, neon signs, flying vehicles, towering skyscrapers, rain-slicked streets, holographic advertisements, Blade Runner inspired',
    style: 'Cinematic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'scifi-space',
    name: 'Space Station',
    description: 'Massive space station orbiting a ringed planet',
    category: 'Sci-Fi',
    prompt: 'A massive space station orbiting a ringed planet, sci-fi concept art, detailed mechanical structures, solar panels, docking ships, realistic space lighting',
    style: '3D Render',
    aspectRatio: '16:9',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'scifi-robot',
    name: 'Futuristic Robot',
    description: 'Sleek humanoid robot with chrome finish and LED eyes',
    category: 'Sci-Fi',
    prompt: 'A sleek futuristic humanoid robot, chrome and matte black finish, glowing LED eyes, advanced mechanical joints, sci-fi character design, studio lighting',
    style: '3D Render',
    aspectRatio: '3:4',
    suggestedStylePreset: '3d-render',
    suggestedAspectRatio: '3:4',
  },

  // ============ Architecture ============
  {
    id: 'architecture-modern',
    name: 'Modern Building',
    description: 'Clean geometric modern architecture at golden hour',
    category: 'Architecture',
    prompt: 'Modern architectural photography, clean geometric lines, glass and steel facade, dramatic perspective, golden hour lighting, minimalist composition, ultra detailed',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'architecture-interior',
    name: 'Luxury Interior',
    description: 'Luxury open-plan interior with designer furniture',
    category: 'Architecture',
    prompt: 'Luxury modern interior design, open floor plan, floor-to-ceiling windows, designer furniture, warm ambient lighting, architectural photography, wide angle',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
  },
  {
    id: 'architecture-gothic',
    name: 'Gothic Cathedral',
    description: 'Gothic cathedral interior with stained glass light',
    category: 'Architecture',
    prompt: 'A gothic cathedral interior, soaring vaulted ceilings, stained glass windows casting colorful light, stone columns, religious atmosphere, dramatic perspective',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Food ============
  {
    id: 'food-plated',
    name: 'Gourmet Plating',
    description: 'Fine dining presentation with artistic garnish',
    category: 'Food',
    prompt: 'A beautifully plated gourmet dish, fine dining presentation, micro herbs garnish, artistic sauce drizzle, shallow depth of field, food photography, warm lighting',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'food-bakery',
    name: 'Artisan Bakery',
    description: 'Fresh artisan bread with warm morning light',
    category: 'Food',
    prompt: 'Fresh artisan bread and pastries on a rustic wooden table, flour dusted surface, warm morning light, cozy bakery atmosphere, food styling, appetizing',
    style: 'Photorealistic',
    aspectRatio: '4:3',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:3',
  },
  {
    id: 'food-cocktail',
    name: 'Craft Cocktail',
    description: 'Elegant cocktail with dramatic backlighting',
    category: 'Food',
    prompt: 'A craft cocktail in an elegant glass, condensation droplets, dramatic backlighting, colorful liquid layers, citrus garnish, bar photography, moody atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Fashion ============
  {
    id: 'fashion-editorial',
    name: 'Fashion Editorial',
    description: 'High fashion Vogue-style editorial photography',
    category: 'Fashion',
    prompt: 'High fashion editorial photography, model in designer outfit, dramatic pose, studio lighting, Vogue-style composition, professional retouching, bold fashion statement',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fashion-streetwear',
    name: 'Street Style',
    description: 'Urban street style with city backdrop',
    category: 'Fashion',
    prompt: 'Urban street style fashion photography, trendy outfit, city background, natural lighting, candid pose, contemporary fashion, lifestyle feel',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'fashion-runway',
    name: 'Runway Moment',
    description: 'Dramatic haute couture runway moment',
    category: 'Fashion',
    prompt: 'A dramatic runway fashion moment, flowing fabric in motion, dramatic stage lighting, model walking with confidence, haute couture, fashion week atmosphere',
    style: 'Cinematic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '3:4',
  },

  // ============ Animals ============
  {
    id: 'animals-wildlife',
    name: 'Wildlife Close-up',
    description: 'Intense wildlife portrait with telephoto bokeh',
    category: 'Animals',
    prompt: 'A stunning wildlife close-up portrait, intense eyes, detailed fur texture, natural habitat background, National Geographic quality, telephoto lens bokeh',
    style: 'Photorealistic',
    aspectRatio: '3:4',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '3:4',
  },
  {
    id: 'animals-pet',
    name: 'Pet Portrait',
    description: 'Adorable pet portrait with soft natural lighting',
    category: 'Animals',
    prompt: 'An adorable pet portrait, soft natural lighting, shallow depth of field, expressive eyes, cozy home environment, heartwarming, professional pet photography',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
  },
  {
    id: 'animals-fantasy',
    name: 'Fantasy Animal',
    description: 'Mythical creature with bioluminescent markings',
    category: 'Animals',
    prompt: 'A majestic fantasy creature combining real and mythical animal features, magical aura, bioluminescent markings, enchanted forest setting, detailed illustration',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
  },

  // =====================================================
  // NEW CATEGORIES — Professional Prompt Templates
  // =====================================================

  // ============ E-commerce & Product Photography ============
  {
    id: 'ecommerce-product-hero',
    name: 'Product Hero Shot',
    description: 'Premium product shot with commercial photography style and brand packaging',
    category: 'E-commerce & Product Photography',
    prompt: 'A premium [PRODUCT] product shot on a [SURFACE] surface with [LIGHTING] lighting, shallow depth of field, commercial photography style, [BRAND] packaging visible, clean [COLOR] background, 8K resolution, photorealistic',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, low quality, distorted, watermark, text overlay',
  },
  {
    id: 'ecommerce-miniature-diorama',
    name: 'Miniature Diorama Ad',
    description: 'Tilt-shift miniature product ad with figurine workers',
    category: 'E-commerce & Product Photography',
    prompt: 'A hyper-realistic miniature diorama product advertisement featuring an oversized [PRODUCT] placed on a circular platform, tiny figurine workers climbing scaffolding around the product, tilt-shift miniature aesthetic, studio photography style, soft diffused lighting, clean background, ultra-detailed',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, noisy, deformed, cartoon, low resolution',
  },
  {
    id: 'ecommerce-flat-lay',
    name: 'Flat Lay Product',
    description: 'Premium flat lay advertisement with ingredients/accessories arrangement',
    category: 'E-commerce & Product Photography',
    prompt: 'Ultra-realistic premium [CATEGORY] advertisement, flat lay composition, soft studio lighting, vibrant [COLOR] background, surrounded by [INGREDIENTS/ACCESSORIES], clean modern typography, luxury branding, high-end commercial photography, 8k detail',
    style: 'Photorealistic',
    aspectRatio: '1:1',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'messy, cluttered, low quality, blurry, distorted',
  },

  // ============ UI & Social Media Mockup ============
  {
    id: 'ui-app-mockup',
    name: 'App UI Mockup',
    description: 'Clean modern mobile app UI with glassmorphism design',
    category: 'UI & Social Media Mockup',
    prompt: 'A clean modern [APP TYPE] mobile app UI mockup, [COLOR SCHEME] color scheme, showing [SCREEN TYPE] screen, glassmorphism design, rounded corners, subtle shadows, SF Pro font style, iOS design language, Dribbble quality',
    style: 'Digital Art',
    aspectRatio: '9:16',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, low quality, unprofessional, cluttered',
  },
  {
    id: 'ui-social-media-post',
    name: 'Social Media Post',
    description: 'Professional social media post design for brand content',
    category: 'UI & Social Media Mockup',
    prompt: 'A professional [PLATFORM] post design for [BRAND], featuring [CONTENT TYPE], modern minimalist layout, [COLOR] accent color, clean typography, eye-catching composition, social media optimized dimensions',
    style: 'Digital Art',
    aspectRatio: '1:1',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'blurry, unprofessional, cluttered, low resolution',
  },
  {
    id: 'ui-dashboard',
    name: 'Dashboard UI',
    description: 'Dark-mode analytics dashboard with glassmorphism cards',
    category: 'UI & Social Media Mockup',
    prompt: 'A dark-mode analytics dashboard UI mockup with [DATA TYPE] charts, sidebar navigation, glassmorphism cards, [ACCENT] accent color, clean data visualization, professional SaaS design, Figma-quality layout',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, low quality, unprofessional, messy layout',
  },

  // ============ Ad Creative & Campaigns ============
  {
    id: 'ad-luxury-product',
    name: 'Luxury Product Ad',
    description: 'Dramatic luxury ad with cinematic light streaks and reflections',
    category: 'Ad Creative & Campaigns',
    prompt: 'A dramatic luxury product advertising image for [PRODUCT] in a dark studio, cinematic [COLOR] and white light streaks, glossy wet ground plane with reflections, ultra-polished commercial photography, high-contrast premium lighting, sleek branding, 8K resolution',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'low quality, blurry, unprofessional, cheap looking, noisy',
  },
  {
    id: 'ad-food-commercial',
    name: 'Food Commercial',
    description: 'Cinematic food hero shot with steam and warm lighting',
    category: 'Ad Creative & Campaigns',
    prompt: 'A cinematic hero image of [FOOD ITEM] on a dark [SURFACE] surface, realistic texture, appetizing steam, warm side light, shallow depth of field, premium food commercial style, no text/logos, 8K',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '4:5',
    negativePrompt: 'unappetizing, blurry, low quality, distorted, text, watermark, logo',
  },
  {
    id: 'ad-brand-campaign',
    name: 'Brand Campaign Poster',
    description: 'Surreal advertising poster with miniature world inside product',
    category: 'Ad Creative & Campaigns',
    prompt: 'A hyper-detailed surreal advertising poster for [BRAND], deep-toned background in brand color, subject holding [PRODUCT], surreal product moment where product opens into miniature world, octane lighting, 8K sharp foreground',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'low quality, blurry, unprofessional, flat, dull',
  },

  // ============ Infographics & Data Visualization ============
  {
    id: 'infographic-poster',
    name: 'Infographic Poster',
    description: 'Engineering-style modular infographic with icons and data modules',
    category: 'Infographics & Data Visualization',
    prompt: 'An engineering-style infographic poster about [TOPIC], modular structure with arrows and icons, information hierarchy, clean [COLOR] and white color scheme, technical illustration style, bilingual labels, data modules, readable layout',
    style: 'Digital Art',
    aspectRatio: '3:4',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'realistic photo, blurry, messy, unprofessional, low quality',
  },
  {
    id: 'infographic-process-diagram',
    name: 'Process Diagram',
    description: 'Clean flowchart-style process diagram with connected nodes',
    category: 'Infographics & Data Visualization',
    prompt: 'A clean process diagram showing [PROCESS NAME], flowchart style with connected nodes, [COLOR] accent arrows, modern iconography, step-by-step layout, professional technical illustration, white background',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, cluttered, unprofessional, low quality',
  },

  // ============ Character Design ============
  {
    id: 'character-sheet',
    name: 'Character Sheet',
    description: 'Multi-view character design sheet with costume details and color palette',
    category: 'Character Design',
    prompt: 'A character design sheet for [CHARACTER TYPE], front/side/back views, consistent style, [ART STYLE] art direction, detailed costume design, color palette swatch, character name label, professional concept art quality',
    style: 'Digital Art',
    aspectRatio: '16:9',
    suggestedStylePreset: 'digital-art',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'realistic photo, blurry, inconsistent, low quality, messy',
  },
  {
    id: 'character-expression-grid',
    name: 'Expression Grid',
    description: '16-panel expression grid showing multiple emotions',
    category: 'Character Design',
    prompt: 'A 16-panel expression grid of [CHARACTER DESCRIPTION], consistent face shape and hairstyle across all panels, showing emotions: happy, sad, angry, surprised, shy, confused, scared, proud, and more, [ART STYLE] style',
    style: 'Anime',
    aspectRatio: '1:1',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '1:1',
    negativePrompt: 'realistic photo, inconsistent faces, blurry, low quality',
  },
  {
    id: 'character-anime-portrait',
    name: 'Anime Character Portrait',
    description: 'Portrait anime illustration with polished rendering and luminous eyes',
    category: 'Character Design',
    prompt: 'Create a portrait-oriented anime illustration of [CHARACTER], [AGE] years old, [EXPRESSION], wearing [OUTFIT], in [SETTING], polished modern anime rendering, crisp line art, luminous eyes, soft cel shading, [MOOD] atmosphere',
    style: 'Anime',
    aspectRatio: '3:4',
    suggestedStylePreset: 'anime',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'realistic photo, blurry, deformed, extra limbs, bad anatomy',
  },

  // ============ Architecture & Interior ============
  {
    id: 'arch-render',
    name: 'Architecture Render',
    description: 'Photorealistic architectural visualization with landscape surroundings',
    category: 'Architecture & Interior',
    prompt: 'A photorealistic architectural rendering of [BUILDING TYPE], [STYLE] style, [TIME OF DAY] lighting, landscaped surroundings, glass and [MATERIAL] facade, professional architecture visualization, Unreal Engine quality, 8K',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, unprofessional, cartoon',
  },
  {
    id: 'arch-interior-design',
    name: 'Interior Design',
    description: 'Luxury interior design with natural light and designer furniture',
    category: 'Architecture & Interior',
    prompt: 'A luxury [ROOM TYPE] interior design, [STYLE] style, [COLOR PALETTE] color scheme, natural light through large windows, [FURNITURE] furniture, plants, professional interior photography, Architectural Digest quality, 8K resolution',
    style: 'Photorealistic',
    aspectRatio: '16:9',
    suggestedStylePreset: 'photorealistic',
    suggestedAspectRatio: '16:9',
    negativePrompt: 'blurry, low quality, distorted, cluttered, unprofessional',
  },

  // ============ Storyboarding & Scene ============
  {
    id: 'storyboard-9-panel',
    name: '9-Panel Storyboard',
    description: 'Professional 9-panel storyboard grid for commercial ads',
    category: 'Storyboarding & Scene',
    prompt: 'A 9-panel storyboard grid for a [DURATION]-second [PRODUCT/SCENE] ad, [ASPECT] format, dark layout with scene titles and timestamps, each panel showing a different camera angle, professional commercial storyboard style, cinematic composition',
    style: 'Cinematic',
    aspectRatio: '9:16',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '9:16',
    negativePrompt: 'realistic photo, blurry, messy, unprofessional, low quality',
  },
  {
    id: 'storyboard-film-still',
    name: 'Film Still',
    description: 'Cinematic film still with professional color grading and lens effects',
    category: 'Storyboarding & Scene',
    prompt: 'A cinematic film still, [GENRE] genre, [SCENE DESCRIPTION], [LIGHTING] lighting, shot on [LENS TYPE], shallow depth of field, color graded in [GRADE STYLE], professional cinematography, anamorphic lens flare, 35mm film grain',
    style: 'Cinematic',
    aspectRatio: '2.39:1',
    suggestedStylePreset: 'cinematic',
    suggestedAspectRatio: '2.39:1',
    negativePrompt: 'amateur, blurry, low quality, unprofessional, flat lighting',
  },

  // ============ Art Styles (Advanced) ============
  {
    id: 'art-watercolor',
    name: 'Watercolor Illustration',
    description: 'Delicate watercolor with soft washes and visible brush texture',
    category: 'Art Styles',
    prompt: 'A delicate watercolor illustration of [SUBJECT], soft color washes, visible brush texture, wet-on-wet technique, [COLOR PALETTE] palette, white paper showing through, fine art quality, traditional watercolor aesthetic',
    style: 'Watercolor',
    aspectRatio: '3:4',
    suggestedStylePreset: 'watercolor',
    suggestedAspectRatio: '3:4',
    negativePrompt: 'photorealistic, digital, sharp edges, heavy, dark, muddy',
  },
];
